#!/usr/bin/env bash
# AsCore — connect an OpenClaw agent (step 3 of "connect in 3 steps"). v3.
#
# Usage (the exact line is generated by AsCore → "Підключити агента"):
#   curl -fsSL https://<ascore>/connect-agent.sh | ASTROCORE_URL=https://<ascore> ASTROCORE_API_KEY=ac_live_... bash
#
# Upgrading a server that is already connected needs no key (it is read from
# /etc/ascore-agent/agent.env):
#   curl -fsSL https://<ascore>/connect-agent.sh | bash
#
# What it does (safe to re-run):
#   1. checks the server (root, openclaw, node 18+, curl)
#   2. enables the OpenClaw Gateway chat endpoint (local only) and reads its token
#   3. checks the Gateway locally
#   4. installs the AsCore MCP tools (reports / memory / gallery)
#   5. installs the AsCore connector (systemd service "ascore-connector").
#      It connects OUT to AsCore and picks up chat messages itself, so the
#      server needs no open ports, domain or HTTPS, and replies have no
#      time limit (up to 30 min per message).
#   6. waits until the agent is online in AsCore
#   7. removes leftovers of the old HTTPS setup (heartbeat timer, Caddy snippet)
#
# Optional overrides:
#   ASCORE_OPENCLAW_CONFIG  path to openclaw.json (default ~/.openclaw/openclaw.json)

set -euo pipefail

ASTROCORE_URL="${ASTROCORE_URL:-https://astrocore-eight.vercel.app}"
ASTROCORE_URL="${ASTROCORE_URL%/}"
ASTROCORE_API_KEY="${ASTROCORE_API_KEY:-}"
OPENCLAW_CONFIG="${ASCORE_OPENCLAW_CONFIG:-$HOME/.openclaw/openclaw.json}"

STATE_DIR="/etc/ascore-agent"
ENV_FILE="${STATE_DIR}/agent.env"
CONNECTOR_DIR="/opt/ascore-connector"
SERVICE="ascore-connector"

# ── output helpers ────────────────────────────────────────────
if [ -t 1 ]; then B=$'\033[1m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; N=$'\033[0m'; else B=""; G=""; Y=""; R=""; N=""; fi
step() { printf '\n%s[%s/7] %s%s\n' "$B" "$1" "$2" "$N"; }
ok()   { printf '  %s✓%s %s\n' "$G" "$N" "$1"; }
warn() { printf '  %s!%s %s\n' "$Y" "$N" "$1"; }
die()  { printf '\n  %s✗ %s%s\n\n' "$R" "$1" "$N" >&2; exit 1; }

json_field() {
  # $1 = field name; JSON on stdin
  node -e '
    let s = "";
    process.stdin.on("data", d => s += d).on("end", () => {
      try { const v = JSON.parse(s)[process.argv[1]]; process.stdout.write(v == null ? "" : String(v)); }
      catch { process.exit(2); }
    });
  ' "$1"
}

# ── 1. checks ─────────────────────────────────────────────────
check_server() {
  step 1 "Перевірка сервера"
  [ "$(id -u)" -eq 0 ] || die "Запусти від root (або через sudo)."

  if [ -z "$ASTROCORE_API_KEY" ] && [ -r "$ENV_FILE" ]; then
    ASTROCORE_API_KEY="$(sed -n 's/^ASTROCORE_API_KEY=//p' "$ENV_FILE" | head -n1)"
    [ -n "$ASTROCORE_API_KEY" ] && ok "Ключ AsCore взято з попереднього підключення"
  fi
  case "$ASTROCORE_API_KEY" in
    ac_live_*) ok "Ключ AsCore є" ;;
    "") die "Немає ASTROCORE_API_KEY. Скопіюй команду повністю з AsCore → «Підключити агента»." ;;
    *)  die "ASTROCORE_API_KEY має починатися з ac_live_." ;;
  esac

  for cmd in openclaw node curl systemctl; do
    command -v "$cmd" >/dev/null 2>&1 || die "Не знайдено «$cmd». Спершу встанови OpenClaw (він ставить і node)."
  done
  node -e 'process.exit(parseInt(process.versions.node, 10) >= 18 ? 0 : 1)' \
    || die "Потрібен Node.js 18 або новіший (зараз $(node -v))."
  [ -f "$OPENCLAW_CONFIG" ] || die "Не знайдено конфіг OpenClaw: $OPENCLAW_CONFIG"
  AGENT_VERSION="$(openclaw --version 2>/dev/null | grep -oE '[0-9]{4}\.[0-9]+\.[0-9]+' | head -n1 || true)"
  ok "OpenClaw ${AGENT_VERSION:-(версію не визначено)}, Node $(node -v)"
}

# ── 2. gateway endpoint + token ───────────────────────────────
read_gateway_field() {
  # $1 = token|port. Reads plain openclaw.json without printing secrets.
  node -e '
    const fs = require("fs");
    let cfg;
    try { cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8")); }
    catch (e) { process.stderr.write("parse"); process.exit(2); }
    const g = cfg.gateway || {};
    if (process.argv[2] === "port") process.stdout.write(String(g.port || 18789));
    else process.stdout.write(String((g.auth || {}).token || ""));
  ' "$OPENCLAW_CONFIG" "$1"
}

setup_gateway() {
  step 2 "Налаштування OpenClaw Gateway"
  openclaw config set gateway.http.endpoints.chatCompletions.enabled true >/dev/null 2>&1 \
    || die "Не вдалося увімкнути chatCompletions. Перевір версію OpenClaw (openclaw --version)."
  ok "Ендпоінт /v1/chat/completions увімкнено (доступний лише на цьому сервері)"
  openclaw gateway restart >/dev/null 2>&1 || systemctl restart openclaw-gateway 2>/dev/null || true
  sleep 3

  GATEWAY_PORT="$(read_gateway_field port)" || die "Не вдалося прочитати $OPENCLAW_CONFIG (не JSON?)."
  GATEWAY_TOKEN="$(read_gateway_field token)" || die "Не вдалося прочитати токен з $OPENCLAW_CONFIG."
  case "$GATEWAY_TOKEN" in
    "")    die "У gateway.auth немає token. Увімкни авторизацію токеном: openclaw config set gateway.auth.mode token" ;;
    '${'*) die "Токен Gateway задано через змінну середовища — вкажи його прямо в gateway.auth.token." ;;
  esac
  [ "${#GATEWAY_TOKEN}" -ge 16 ] || die "Токен Gateway закороткий (менше 16 символів)."
  ok "Токен Gateway знайдено (${#GATEWAY_TOKEN} символів), порт $GATEWAY_PORT"
}

# ── 3. local check (no model call — an empty body is enough to test auth) ──
http_code() {
  local c
  c="$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$@" 2>/dev/null)" || true
  printf '%s' "${c:-000}"
}

check_gateway_local() {
  step 3 "Перевірка Gateway на сервері"
  local code="000" i
  for i in 1 2 3 4 5 6; do
    code="$(http_code -X POST "http://127.0.0.1:${GATEWAY_PORT}/v1/chat/completions" \
      -H "Authorization: Bearer ${GATEWAY_TOKEN}" -H "Content-Type: application/json" -d '{}')"
    [ "$code" != "000" ] && break
    sleep 2
  done
  case "$code" in
    000) die "Gateway не відповідає на 127.0.0.1:${GATEWAY_PORT}. Перевір: systemctl status openclaw-gateway" ;;
    401|403) die "Gateway відхилив токен (HTTP $code)." ;;
    404) die "Gateway не віддає /v1/chat/completions (404). Перезапусти: openclaw gateway restart — і запусти скрипт ще раз." ;;
    *) ok "Gateway відповідає і приймає токен (HTTP $code)" ;;
  esac
}

# ── 4. MCP tools ──────────────────────────────────────────────
setup_mcp() {
  step 4 "Інструменти AsCore для агента (MCP)"
  local mcp_script
  mcp_script="$(mktemp)"
  if curl -fsSL --max-time 30 "${ASTROCORE_URL}/connect-mcp.sh" -o "$mcp_script" 2>/dev/null; then
    if ASTROCORE_URL="$ASTROCORE_URL" ASTROCORE_API_KEY="$ASTROCORE_API_KEY" bash "$mcp_script"; then
      ok "MCP встановлено"
    else
      warn "Встановлення MCP завершилось з помилкою — чат працюватиме, але агент поки не бачить звіти/пам'ять/галерею"
    fi
  else
    warn "Не знайшов ${ASTROCORE_URL}/connect-mcp.sh — MCP пропущено"
  fi
  rm -f "$mcp_script"
}

# ── 5. connector ──────────────────────────────────────────────
install_connector() {
  step 5 "AsCore конектор"

  local cfg sb_url sb_key
  cfg="$(curl -fsS --max-time 20 "${ASTROCORE_URL}/api/agents/config" 2>/dev/null)" \
    || die "Не вдалося отримати налаштування з ${ASTROCORE_URL}/api/agents/config"
  sb_url="$(printf '%s' "$cfg" | json_field supabaseUrl)" || die "AsCore повернув некоректні налаштування."
  sb_key="$(printf '%s' "$cfg" | json_field supabaseKey)" || die "AsCore повернув некоректні налаштування."
  [ -n "$sb_url" ] && [ -n "$sb_key" ] || die "AsCore повернув неповні налаштування."

  install -d -m 755 "$CONNECTOR_DIR"
  curl -fsSL --max-time 30 "${ASTROCORE_URL}/ascore-connector.mjs" -o "${CONNECTOR_DIR}/connector.mjs.new" \
    || die "Не вдалося завантажити ${ASTROCORE_URL}/ascore-connector.mjs"
  node --check "${CONNECTOR_DIR}/connector.mjs.new" >/dev/null 2>&1 \
    || { rm -f "${CONNECTOR_DIR}/connector.mjs.new"; die "Завантажений конектор пошкоджений."; }
  mv -f "${CONNECTOR_DIR}/connector.mjs.new" "${CONNECTOR_DIR}/connector.mjs"
  chmod 644 "${CONNECTOR_DIR}/connector.mjs"
  ok "Конектор завантажено"

  install -d -m 700 "$STATE_DIR"
  (
    umask 077
    cat > "$ENV_FILE" <<EOF
ASTROCORE_URL=${ASTROCORE_URL}
ASTROCORE_API_KEY=${ASTROCORE_API_KEY}
SUPABASE_URL=${sb_url}
SUPABASE_KEY=${sb_key}
GATEWAY_PORT=${GATEWAY_PORT}
GATEWAY_TOKEN=${GATEWAY_TOKEN}
EOF
  )
  chmod 600 "$ENV_FILE"

  local node_bin
  node_bin="$(command -v node)"
  cat > "/etc/systemd/system/${SERVICE}.service" <<EOF
[Unit]
Description=AsCore connector (OpenClaw agent <-> AsCore chat)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=${ENV_FILE}
Environment=PATH=$(dirname "$node_bin"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=${node_bin} ${CONNECTOR_DIR}/connector.mjs
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable "$SERVICE" >/dev/null 2>&1
  CONNECTOR_STARTED_AT="$(date +%s)"
  systemctl restart "$SERVICE"
  ok "Сервіс ${SERVICE} запущено і додано в автозапуск"
}

# ── 6. wait until online ──────────────────────────────────────
wait_online() {
  step 6 "Підключення до AsCore"
  local i
  for i in $(seq 1 20); do
    if journalctl -u "$SERVICE" --since "@${CONNECTOR_STARTED_AT}" -o cat 2>/dev/null | grep -q "ASCORE_CONNECTOR_READY"; then
      ok "Агент онлайн в AsCore"
      return 0
    fi
    sleep 1.5
  done
  printf '\n'
  journalctl -u "$SERVICE" --since "@${CONNECTOR_STARTED_AT}" -n 20 -o cat 2>/dev/null || true
  die "Конектор не підключився за 30 с (лог вище). Перевір: journalctl -u ${SERVICE} -n 50"
}

# ── 7. leftovers of the old HTTPS scheme ──────────────────────
cleanup_legacy() {
  step 7 "Прибирання старої схеми"
  local cleaned=0

  if [ -f /etc/systemd/system/ascore-agent-heartbeat.timer ]; then
    systemctl disable --now ascore-agent-heartbeat.timer >/dev/null 2>&1 || true
    rm -f /etc/systemd/system/ascore-agent-heartbeat.timer \
          /etc/systemd/system/ascore-agent-heartbeat.service \
          /usr/local/bin/ascore-agent-heartbeat
    systemctl daemon-reload
    ok "Старий heartbeat вимкнено (статус тепер передає конектор)"
    cleaned=1
  fi

  if [ -f /etc/caddy/ascore/agent.caddy ] && grep -q "reverse_proxy" /etc/caddy/ascore/agent.caddy; then
    printf '# AsCore agent no longer needs a public address (connector v3). This file can stay empty.\n' \
      > /etc/caddy/ascore/agent.caddy
    if command -v caddy >/dev/null 2>&1 && caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
      systemctl reload caddy >/dev/null 2>&1 || true
      ok "Публічну HTTPS-адресу агента закрито (інші сайти в Caddy не змінено)"
    else
      warn "Caddyfile не пройшов перевірку після змін — подивись: caddy validate --config /etc/caddy/Caddyfile"
    fi
    cleaned=1
  fi

  [ "$cleaned" -eq 1 ] || ok "Нічого прибирати"
}

main() {
  printf '%sAsCore · підключення OpenClaw агента%s\n' "$B" "$N"
  check_server
  setup_gateway
  check_gateway_local
  setup_mcp
  install_connector
  wait_online
  cleanup_legacy
  printf '\n%s✓ Готово.%s Відкрий AsCore і напиши агенту.\n  Лог: journalctl -u %s -f\n\n' "$G" "$N" "$SERVICE"
}

main "$@"