#!/usr/bin/env bash
# AsCore — connect an OpenClaw agent (step 3 of "connect in 3 steps").
#
# Usage (the exact line is generated by AsCore → "Підключити агента"):
#   curl -fsSL https://<ascore>/connect-agent.sh | ASTROCORE_URL=https://<ascore> ASTROCORE_API_KEY=ac_live_... bash
#
# What it does (safe to re-run):
#   1. checks the server (root, openclaw, node, curl)
#   2. enables the OpenClaw Gateway chat endpoint and reads its token
#   3. checks the Gateway locally
#   4. publishes ONLY POST /v1/chat/completions over HTTPS (Caddy + sslip.io);
#      everything else on that address answers 404
#   5. installs the AsCore MCP tools (reports / memory / gallery)
#   6. registers the agent in AsCore
#   7. installs a heartbeat timer so AsCore shows online/offline
#
# Optional overrides:
#   ASCORE_AGENT_DOMAIN     use your own domain instead of ascore.<ip>.sslip.io
#   ASCORE_OPENCLAW_CONFIG  path to openclaw.json (default ~/.openclaw/openclaw.json)

set -euo pipefail

ASTROCORE_URL="${ASTROCORE_URL:-https://astrocore-eight.vercel.app}"
ASTROCORE_URL="${ASTROCORE_URL%/}"
ASTROCORE_API_KEY="${ASTROCORE_API_KEY:-}"
OPENCLAW_CONFIG="${ASCORE_OPENCLAW_CONFIG:-$HOME/.openclaw/openclaw.json}"

STATE_DIR="/etc/ascore-agent"
CADDY_SNIPPET_DIR="/etc/caddy/ascore"
CADDYFILE="/etc/caddy/Caddyfile"

# ── output helpers ────────────────────────────────────────────
if [ -t 1 ]; then B=$'\033[1m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; N=$'\033[0m'; else B=""; G=""; Y=""; R=""; N=""; fi
step() { printf '\n%s[%s/7] %s%s\n' "$B" "$1" "$2" "$N"; }
ok()   { printf '  %s✓%s %s\n' "$G" "$N" "$1"; }
warn() { printf '  %s!%s %s\n' "$Y" "$N" "$1"; }
die()  { printf '\n  %s✗ %s%s\n\n' "$R" "$1" "$N" >&2; exit 1; }

# ── 1. checks ─────────────────────────────────────────────────
check_server() {
  step 1 "Перевірка сервера"
  [ "$(id -u)" -eq 0 ] || die "Запусти від root (або через sudo)."
  case "$ASTROCORE_API_KEY" in
    ac_live_*) ok "Ключ AsCore отримано" ;;
    "") die "Немає ASTROCORE_API_KEY. Скопіюй команду повністю з AsCore → «Підключити агента»." ;;
    *)  die "ASTROCORE_API_KEY має починатися з ac_live_." ;;
  esac
  for cmd in openclaw node curl; do
    command -v "$cmd" >/dev/null 2>&1 || die "Не знайдено «$cmd». Спершу встанови OpenClaw (він ставить і node)."
  done
  [ -f "$OPENCLAW_CONFIG" ] || die "Не знайдено конфіг OpenClaw: $OPENCLAW_CONFIG"
  AGENT_VERSION="$(openclaw --version 2>/dev/null | grep -oE '[0-9]{4}\.[0-9]+\.[0-9]+' | head -n1 || true)"
  ok "OpenClaw ${AGENT_VERSION:-(версію не визначено)}"
}

# ── 2. gateway endpoint + token ───────────────────────────────
read_gateway_field() {
  # $1 = token|port. Plain JSON is what OpenClaw writes; reads it without printing secrets anywhere else.
  node -e '
    const fs = require("fs");
    let cfg;
    try { cfg = JSON.parse(fs.readFileSync(process.argv[1], "utf8")); }
    catch (e) { process.stderr.write("parse"); process.exit(2); }
    const g = cfg.gateway || {};
    if (process.argv[2] === "port") process.stdout.write(String(g.port || 18789));
    else process.stdout.write(String((g.auth || {}).token || ""));
  ' "$OPENCLAW_CONFIG" "$1"
}

setup_gateway() {
  step 2 "Налаштування OpenClaw Gateway"
  openclaw config set gateway.http.endpoints.chatCompletions.enabled true >/dev/null 2>&1 \
    || die "Не вдалося увімкнути chatCompletions. Перевір версію OpenClaw (openclaw --version)."
  ok "Ендпоінт /v1/chat/completions увімкнено"

  # Caddy runs on this same machine, so only loopback is a trusted proxy.
  # Without this the Gateway rejects proxied requests (proxy_attribution_required).
  openclaw config set gateway.trustedProxies '["127.0.0.1","::1"]' >/dev/null 2>&1 \
    || die "Не вдалося задати gateway.trustedProxies."
  ok "Довірений проксі: лише локальний Caddy (127.0.0.1)"
  openclaw gateway restart >/dev/null 2>&1 || systemctl restart openclaw-gateway 2>/dev/null || true
  sleep 3

  GATEWAY_PORT="$(read_gateway_field port)" || die "Не вдалося прочитати $OPENCLAW_CONFIG (не JSON?)."
  GATEWAY_TOKEN="$(read_gateway_field token)" || die "Не вдалося прочитати токен з $OPENCLAW_CONFIG."
  case "$GATEWAY_TOKEN" in
    "")    die "У gateway.auth немає token. Увімкни авторизацію токеном: openclaw config set gateway.auth.mode token" ;;
    '${'*) die "Токен Gateway задано через змінну середовища — вкажи його прямо в gateway.auth.token." ;;
  esac
  [ "${#GATEWAY_TOKEN}" -ge 16 ] || die "Токен Gateway закороткий (менше 16 символів)."
  ok "Токен Gateway знайдено (${#GATEWAY_TOKEN} символів), порт $GATEWAY_PORT"
}

# ── 3. local check (no model call — an empty body is enough to test auth) ──
# curl -w already prints 000 when it can't connect; `|| true` only swallows the exit code.
http_code() {
  local c
  c="$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$@" 2>/dev/null)" || true
  printf '%s' "${c:-000}"
}

check_gateway_local() {
  step 3 "Перевірка Gateway на сервері"
  local code="000" i
  for i in 1 2 3 4 5 6; do
    code="$(http_code -X POST "http://127.0.0.1:${GATEWAY_PORT}/v1/chat/completions" \
      -H "Authorization: Bearer ${GATEWAY_TOKEN}" -H "Content-Type: application/json" -d '{}')"
    [ "$code" != "000" ] && break
    sleep 2
  done
  case "$code" in
    000) die "Gateway не відповідає на 127.0.0.1:${GATEWAY_PORT}. Перевір: systemctl status openclaw-gateway" ;;
    401|403) die "Gateway відхилив токен (HTTP $code)." ;;
    404) die "Gateway не віддає /v1/chat/completions (404). Перезапусти: openclaw gateway restart — і запусти скрипт ще раз." ;;
    *) ok "Gateway відповідає і приймає токен (HTTP $code)" ;;
  esac
}

# ── 4. HTTPS via Caddy ────────────────────────────────────────
install_caddy() {
  command -v caddy >/dev/null 2>&1 && return 0
  command -v apt-get >/dev/null 2>&1 || die "Caddy не встановлено, а автоматично ставлю лише на Ubuntu/Debian."
  warn "Caddy не знайдено — встановлюю"
  apt-get update -qq
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https gnupg >/dev/null
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy >/dev/null
  ok "Caddy встановлено"
}

detect_domain() {
  if [ -n "${ASCORE_AGENT_DOMAIN:-}" ]; then AGENT_DOMAIN="$ASCORE_AGENT_DOMAIN"; return; fi
  local ip
  ip="$(curl -4 -fsS --max-time 10 https://api.ipify.org 2>/dev/null || curl -4 -fsS --max-time 10 https://ifconfig.me 2>/dev/null || true)"
  [[ "$ip" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]] || die "Не вдалося визначити публічну IP. Задай домен вручну: ASCORE_AGENT_DOMAIN=agent.example.com"
  AGENT_DOMAIN="ascore.${ip//./-}.sslip.io"
}

setup_https() {
  step 4 "Публічна HTTPS-адреса для AsCore"
  detect_domain
  ok "Адреса агента: https://${AGENT_DOMAIN}"

  local busy
  busy="$(ss -ltnpH '( sport = :443 )' 2>/dev/null | grep -v caddy || true)"
  [ -z "$busy" ] || die "Порт 443 зайнятий іншою програмою (не Caddy): $busy"

  install_caddy
  mkdir -p "$CADDY_SNIPPET_DIR"
  cat > "${CADDY_SNIPPET_DIR}/agent.caddy" <<EOF
# Managed by AsCore connect-agent.sh — re-running the script rewrites this file.
# Only POST /v1/chat/completions reaches the OpenClaw Gateway; everything else is 404.
${AGENT_DOMAIN} {
	@chat {
		method POST
		path /v1/chat/completions
	}
	handle @chat {
		reverse_proxy 127.0.0.1:${GATEWAY_PORT} {
			header_up X-Forwarded-For {remote_host}
			header_up X-Real-IP {remote_host}
			flush_interval -1
		}
	}
	handle {
		respond "Not found" 404
	}
}
EOF
  touch "$CADDYFILE"
  if ! grep -qF "import ${CADDY_SNIPPET_DIR}/*.caddy" "$CADDYFILE"; then
    printf '\n# AsCore agent (connect-agent.sh)\nimport %s/*.caddy\n' "$CADDY_SNIPPET_DIR" >> "$CADDYFILE"
  fi
  caddy validate --config "$CADDYFILE" --adapter caddyfile >/dev/null 2>&1 \
    || die "Caddyfile не пройшов перевірку. Подивись: caddy validate --config $CADDYFILE"

  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
    ufw allow 80/tcp >/dev/null && ufw allow 443/tcp >/dev/null && ok "Відкрито порти 80/443 в ufw"
  fi

  systemctl enable caddy >/dev/null 2>&1 || true
  if systemctl is-active --quiet caddy; then systemctl reload caddy; else systemctl restart caddy; fi
  ok "Caddy налаштовано (bridge та інші сайти в Caddyfile не змінено)"

  printf '  … чекаю на HTTPS-сертифікат'
  local code="000" i
  for i in $(seq 1 40); do
    code="$(http_code -X POST "https://${AGENT_DOMAIN}/v1/chat/completions" \
      -H "Authorization: Bearer ${GATEWAY_TOKEN}" -H "Content-Type: application/json" -d '{}')"
    case "$code" in 000|502|503) printf '.'; sleep 3 ;; *) break ;; esac
  done
  printf '\n'
  case "$code" in
    000|502|503) die "https://${AGENT_DOMAIN} не відповідає (HTTP $code). Перевір: journalctl -u caddy -n 50" ;;
    401|403|404) die "Публічна адреса відповідає, але не доходить до Gateway (HTTP $code)." ;;
    *) ok "Агент доступний ззовні по HTTPS (HTTP $code)" ;;
  esac
  local other
  other="$(http_code "https://${AGENT_DOMAIN}/")"
  [ "$other" = "404" ] && ok "Решта Gateway ззовні закрита (/ → 404)" || warn "Очікував 404 на «/», отримав $other"
}

# ── 5. MCP tools ──────────────────────────────────────────────
setup_mcp() {
  step 5 "Інструменти AsCore для агента (MCP)"
  local mcp_script
  mcp_script="$(mktemp)"
  if curl -fsSL --max-time 30 "${ASTROCORE_URL}/connect-mcp.sh" -o "$mcp_script" 2>/dev/null; then
    if ASTROCORE_URL="$ASTROCORE_URL" ASTROCORE_API_KEY="$ASTROCORE_API_KEY" bash "$mcp_script"; then
      ok "MCP встановлено"
    else
      warn "Встановлення MCP завершилось з помилкою — чат працюватиме, але агент поки не бачить звіти/пам'ять/галерею"
    fi
  else
    warn "Не знайшов ${ASTROCORE_URL}/connect-mcp.sh — MCP пропущено"
  fi
  rm -f "$mcp_script"
}

# ── 6. register in AsCore ─────────────────────────────────────
register_agent() {
  step 6 "Реєстрація агента в AsCore"
  local body resp code
  body="$(ENDPOINT="https://${AGENT_DOMAIN}/v1" TOKEN="$GATEWAY_TOKEN" VERSION="${AGENT_VERSION:-}" node -e '
    process.stdout.write(JSON.stringify({
      endpointUrl: process.env.ENDPOINT,
      gatewayToken: process.env.TOKEN,
      agentVersion: process.env.VERSION || null,
    }))')"
  resp="$(mktemp)"
  code="$(curl -s -o "$resp" -w '%{http_code}' --max-time 30 -X POST "${ASTROCORE_URL}/api/agents/register" \
    -H "X-Api-Key: ${ASTROCORE_API_KEY}" -H "Content-Type: application/json" --data-binary "$body" 2>/dev/null)" || true
  code="${code:-000}"
  case "$code" in
    200) ok "Агента зареєстровано — у чаті AsCore він тепер «підключено»" ;;
    401) rm -f "$resp"; die "AsCore не прийняв ключ (401). Створи нове підключення в AsCore і скопіюй свіжу команду." ;;
    409) rm -f "$resp"; die "Цей ключ не для підключення агента (409). Використай команду з кнопки «Підключити агента»." ;;
    *)   local msg; msg="$(head -c 300 "$resp")"; rm -f "$resp"; die "AsCore повернув HTTP $code: $msg" ;;
  esac
  rm -f "$resp"
}

# ── 7. heartbeat ──────────────────────────────────────────────
setup_heartbeat() {
  step 7 "Статус онлайн (heartbeat)"
  install -d -m 700 "$STATE_DIR"
  umask 077
  cat > "${STATE_DIR}/agent.env" <<EOF
ASTROCORE_URL=${ASTROCORE_URL}
ASTROCORE_API_KEY=${ASTROCORE_API_KEY}
EOF
  chmod 600 "${STATE_DIR}/agent.env"

  cat > /usr/local/bin/ascore-agent-heartbeat <<'EOF'
#!/usr/bin/env bash
# Tells AsCore this agent is alive. Installed by connect-agent.sh.
set -eu
. /etc/ascore-agent/agent.env
VERSION="$(openclaw --version 2>/dev/null | grep -oE '[0-9]{4}\.[0-9]+\.[0-9]+' | head -n1 || true)"
curl -fsS --max-time 20 -X POST "${ASTROCORE_URL}/api/agents/heartbeat" \
  -H "X-Api-Key: ${ASTROCORE_API_KEY}" -H "Content-Type: application/json" \
  -d "{\"agentVersion\":\"${VERSION}\"}" >/dev/null
EOF
  chmod 755 /usr/local/bin/ascore-agent-heartbeat

  cat > /etc/systemd/system/ascore-agent-heartbeat.service <<'EOF'
[Unit]
Description=AsCore agent heartbeat
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ascore-agent-heartbeat
EOF

  cat > /etc/systemd/system/ascore-agent-heartbeat.timer <<'EOF'
[Unit]
Description=AsCore agent heartbeat every 5 minutes

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Persistent=true

[Install]
WantedBy=timers.target
EOF

  systemctl daemon-reload
  systemctl enable --now ascore-agent-heartbeat.timer >/dev/null 2>&1
  if /usr/local/bin/ascore-agent-heartbeat; then ok "Heartbeat працює (кожні 5 хв)"; else warn "Перший heartbeat не пройшов — таймер спробує ще раз"; fi
}

main() {
  printf '%sAsCore · підключення OpenClaw агента%s\n' "$B" "$N"
  check_server
  setup_gateway
  check_gateway_local
  setup_https
  setup_mcp
  register_agent
  setup_heartbeat
  printf '\n%s✓ Готово.%s Відкрий AsCore — агент з'"'"'явиться в чаті.\n  Адреса агента: https://%s\n\n' "$G" "$N" "$AGENT_DOMAIN"
}

main "$@"