// ============================================================
// AstroCore i18n dictionary.
//
// To add a new language later (Polish, German, Spanish, French...):
//   1. Add its code to the `Language` union below.
//   2. Add an entry to `LANGUAGES`.
//   3. Add a full translation object below, typed as `typeof uk` —
//      TypeScript will error out at compile time if any key is missing,
//      so it's impossible to ship a half-translated language by accident.
//   No component needs to change.
// ============================================================

export type Language = "uk" | "en"

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "uk", label: "Українська", flag: "🇺🇦" },
  { code: "en", label: "English", flag: "🇺🇸" },
]

export const DEFAULT_LANGUAGE: Language = "uk"

const uk = {
  common: {
    save: "Зберегти",
    cancel: "Скасувати",
    loading: "Завантаження...",
  },
  sidebar: {
    center: "Центр",
    chat: "Чат",
    agents: "Агенти",
    memory: "Пам'ять",
    vault: "Сховище",
    gallery: "Галерея",
    integrations: "Інтеграції",
    settings: "Налаштування",
    providers: "Провайдери",
    back: "Назад",
    contact: "Зв'язок",
    contactSubtitle: "Напишіть нам у зручному каналі",
    telegramSubtitle: "Швидка відповідь",
    yourPlan: "Твій план",
    upgrade: "Покращити",
    account: "Акаунт",
    signOut: "Вийти",
  },
  dashboard: {
    onlineBadge: "AI CORE — ОНЛАЙН",
    greetingMorning: "Добрий ранок",
    greetingDay: "Добрий день",
    greetingEvening: "Добрий вечір",
    newAgent: "Новий агент",
    openChat: "Відкрити чат",
    addApiKey: "Додайте API ключ",
    addApiKeyBanner: "Додайте API ключ, щоб агенти могли відповідати",
    statAgents: "Агенти",
    statAgentsSub: "активних",
    statSessions: "Сесії",
    statSessionsSub: "розмов",
    statProviders: "Провайдери",
    statProvidersSub: "підключено",
    statVault: "Сховище",
    statVaultSub: "записів",
    statMemory: "Пам'ять",
    statMemorySub: "записів",
    statGallery: "Галерея",
    statGallerySub: "виводів",
    agentsPanel: "Агенти",
    allAgents: "Всі агенти",
    noAgents: "Агентів ще немає",
    createAgent: "Створити агента",
    createNewAgent: "Створити нового агента",
    recentChats: "Останні чати",
    allSessions: "Всі сесії",
    noSessions: "Сесій ще немає",
    newChat: "Новий чат",
    openNewChat: "Відкрити новий чат",
    knowledgeVault: "Сховище знань",
    open: "Відкрити",
    emptyVault: "Сховище порожнє",
    providersPanel: "Провайдери",
    manage: "Керувати",
    noProviders: "Провайдерів немає",
    active: "Активний",
    inactive: "Вимкнено",
    quickActions: "Швидкі дії",
    recentActivity: "Остання активність",
    activityNewAgent: "Створено нового агента",
    activityNewSession: "Створено нову сесію",
    activitySavedVault: "Збережено запис",
  },
  login: {
    title: "Вхід",
    email: "Електронна пошта",
    password: "Пароль",
    forgotPassword: "Забули пароль?",
    signIn: "Увійти",
    noAccount: "Немає акаунта?",
    createOne: "Зареєструватись",
  },
  register: {
    title: "Створити акаунт",
    name: "Ім'я",
    email: "Електронна пошта",
    password: "Пароль",
    confirmPassword: "Підтвердіть пароль",
    alreadyHaveAccount: "Вже є акаунт?",
    signIn: "Увійти",
    createAccount: "Створити акаунт",
  },
  settings: {
    language: "Мова",
    languageDesc: "Оберіть мову інтерфейсу AstroCore.",
  },
}

const en: typeof uk = {
  common: {
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
  },
  sidebar: {
    center: "Center",
    chat: "Chat",
    agents: "Agents",
    memory: "Memory",
    vault: "Vault",
    gallery: "Gallery",
    integrations: "Integrations",
    settings: "Settings",
    providers: "Providers",
    back: "Back",
    contact: "Contact",
    contactSubtitle: "Message us on your preferred channel",
    telegramSubtitle: "Quick reply",
    yourPlan: "Your plan",
    upgrade: "Upgrade",
    account: "Account",
    signOut: "Sign out",
  },
  dashboard: {
    onlineBadge: "AI CORE — ONLINE",
    greetingMorning: "Good morning",
    greetingDay: "Good afternoon",
    greetingEvening: "Good evening",
    newAgent: "New agent",
    openChat: "Open chat",
    addApiKey: "Add API key",
    addApiKeyBanner: "Add an API key so agents can respond",
    statAgents: "Agents",
    statAgentsSub: "active",
    statSessions: "Sessions",
    statSessionsSub: "conversations",
    statProviders: "Providers",
    statProvidersSub: "connected",
    statVault: "Vault",
    statVaultSub: "entries",
    statMemory: "Memory",
    statMemorySub: "entries",
    statGallery: "Gallery",
    statGallerySub: "outputs",
    agentsPanel: "Agents",
    allAgents: "All agents",
    noAgents: "No agents yet",
    createAgent: "Create agent",
    createNewAgent: "Create a new agent",
    recentChats: "Recent chats",
    allSessions: "All sessions",
    noSessions: "No sessions yet",
    newChat: "New chat",
    openNewChat: "Open a new chat",
    knowledgeVault: "Knowledge vault",
    open: "Open",
    emptyVault: "Vault is empty",
    providersPanel: "Providers",
    manage: "Manage",
    noProviders: "No providers",
    active: "Active",
    inactive: "Disabled",
    quickActions: "Quick actions",
    recentActivity: "Recent activity",
    activityNewAgent: "Created a new agent",
    activityNewSession: "Started a new session",
    activitySavedVault: "Saved an entry",
  },
  login: {
    title: "Login",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign in",
    noAccount: "Don't have an account?",
    createOne: "Sign up",
  },
  register: {
    title: "Create account",
    name: "Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
    createAccount: "Create account",
  },
  settings: {
    language: "Language",
    languageDesc: "Choose the AstroCore interface language.",
  },
}

export const translations: Record<Language, typeof uk> = { uk, en }