// ============================================================
// AstroCore i18n dictionary.
//
// To add a new language later (Polish, German, Spanish, French...):
//   1. Add its code to the `Language` union below.
//   2. Add an entry to `LANGUAGES`.
//   3. Add a full translation object below, typed as `typeof uk` —
//      TypeScript will error out at compile time if any key is missing,
//      so it's impossible to ship a half-translated language by accident.
//   No component needs to change.
// ============================================================

export type Language = "uk" | "en"

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "uk", label: "Українська", flag: "🇺🇦" },
  { code: "en", label: "English", flag: "🇺🇸" },
]

export const DEFAULT_LANGUAGE: Language = "uk"

const uk = {
  common: {
    save: "Зберегти",
    cancel: "Скасувати",
    loading: "Завантаження...",
  },
  sidebar: {
    center: "Центр",
    chat: "Чат",
    agents: "Агенти",
    memory: "Пам'ять",
    vault: "Сховище",
    gallery: "Галерея",
    forum: "Форум",
    integrations: "Інтеграції",
    settings: "Налаштування",
    providers: "Провайдери",
    back: "Назад",
    contact: "Зв'язок",
    contactSubtitle: "Напишіть нам у зручному каналі",
    telegramSubtitle: "Швидка відповідь",
    yourPlan: "Твій план",
    upgrade: "Покращити",
    account: "Акаунт",
    signOut: "Вийти",
  },
  dashboard: {
    onlineBadge: "AI CORE — ОНЛАЙН",
    greetingMorning: "Добрий ранок",
    greetingDay: "Добрий день",
    greetingEvening: "Добрий вечір",
    newAgent: "Новий агент",
    openChat: "Відкрити чат",
    addApiKey: "Додайте API ключ",
    addApiKeyBanner: "Додайте API ключ, щоб агенти могли відповідати",
    statAgents: "Агенти",
    statAgentsSub: "активних",
    statSessions: "Сесії",
    statSessionsSub: "розмов",
    statProviders: "Провайдери",
    statProvidersSub: "підключено",
    statVault: "Сховище",
    statVaultSub: "записів",
    statMemory: "Пам'ять",
    statMemorySub: "записів",
    statGallery: "Галерея",
    statGallerySub: "виводів",
    agentsPanel: "Агенти",
    allAgents: "Всі агенти",
    noAgents: "Агентів ще немає",
    createAgent: "Створити агента",
    createNewAgent: "Створити нового агента",
    recentChats: "Останні чати",
    allSessions: "Всі сесії",
    noSessions: "Сесій ще немає",
    newChat: "Новий чат",
    openNewChat: "Відкрити новий чат",
    knowledgeVault: "Сховище знань",
    open: "Відкрити",
    emptyVault: "Сховище порожнє",
    providersPanel: "Провайдери",
    manage: "Керувати",
    noProviders: "Провайдерів немає",
    active: "Активний",
    inactive: "Вимкнено",
    quickActions: "Швидкі дії",
    recentActivity: "Остання активність",
    activityNewAgent: "Створено нового агента",
    activityNewSession: "Створено нову сесію",
    activitySavedVault: "Збережено запис",
  },
  login: {
    title: "Вхід",
    email: "Електронна пошта",
    password: "Пароль",
    forgotPassword: "Забули пароль?",
    signIn: "Увійти",
    noAccount: "Немає акаунта?",
    createOne: "Зареєструватись",
  },
  register: {
    title: "Створити акаунт",
    name: "Ім'я",
    email: "Електронна пошта",
    password: "Пароль",
    confirmPassword: "Підтвердіть пароль",
    alreadyHaveAccount: "Вже є акаунт?",
    signIn: "Увійти",
    createAccount: "Створити акаунт",
  },
  settings: {
    language: "Мова",
    languageDesc: "Оберіть мову інтерфейсу AstroCore.",
    subtitleTagline: "AI Operating Layer · Workspace Settings · System Control",
    statAgents: "агентів",
    statChats: "чатів",
    statProviders: "провайдерів",
    statVault: "у сховищі",
    statGallery: "у галереї",
    clearedSuffix: "успішно очищено",
    sectionsTitle: "Розділи",
    accountDesc: "Профіль, аватар, особиста інформація",
    providersDesc: "API ключі, підключені AI моделі",
    memoryDesc: "Контекст і знання що інжектуються в агентів",
    vaultDesc: "Збережені знання та нотатки",
    galleryDesc: "Збережені виводи AI",
    devCenterLabel: "Developer Center",
    devCenterDesc: "API Keys, Webhooks, Integrations and Developer tools.",
    systemStatusTitle: "Статус системи",
    aiCoreLabel: "AI Core",
    onlineLabel: "Онлайн",
    localStorageLabel: "localStorage",
    availableLabel: "Доступно",
    providersStatusLabel: "Провайдери",
    connectedSuffix: "підключено",
    noneLabel: "Немає",
    activeAgentsLabel: "Активні агенти",
    agentsCountSuffix: "агентів",
    securityTitle: "Безпека та приватність",
    securityDesc: "Всі дані зберігаються локально у вашому браузері. API ключі, агенти, чати і вся пам'ять — тільки у вашому localStorage. Жодних зовнішніх серверів.",
    apiKeysLabel: "API ключі",
    apiKeysDesc: "Перейти до налаштування провайдерів",
    dataManagementTitle: "Управління даними",
    clearAgentsLabel: "Очистити агентів",
    clearAgentsDescPrefix: "Видалити всіх ",
    clearAgentsDescSuffix: " агентів назавжди",
    clearAgentsConfirmTitle: "Очистити агентів?",
    clearAgentsConfirmDesc: "Всі агенти будуть видалені назавжди. Це неможливо скасувати.",
    agentsName: "Агенти",
    clearChatsLabel: "Очистити чати",
    clearChatsDescPrefix: "Видалити всі ",
    clearChatsDescSuffix: " сесії назавжди",
    clearChatsConfirmTitle: "Очистити чати?",
    clearChatsConfirmDesc: "Всі чати будуть видалені назавжди. Це неможливо скасувати.",
    chatsName: "Чати",
    clearMemoryLabel: "Очистити пам'ять",
    clearMemoryDesc: "Видалити весь контекст та знання",
    clearMemoryConfirmTitle: "Очистити пам'ять?",
    clearMemoryConfirmDesc: "Весь контекст та знання будуть видалені назавжди. Це неможливо скасувати.",
    memoryName: "Пам'ять",
    clearVaultLabel: "Очистити сховище",
    clearVaultDescPrefix: "Видалити всі ",
    clearVaultDescSuffix: " записи",
    clearVaultConfirmTitle: "Очистити сховище?",
    clearVaultConfirmDesc: "Всі записи сховища будуть видалені назавжди. Це неможливо скасувати.",
    vaultName: "Сховище",
    clearGalleryLabel: "Очистити галерею",
    clearGalleryDescPrefix: "Видалити всі ",
    clearGalleryDescSuffix: " виводів",
    clearGalleryConfirmTitle: "Очистити галерею?",
    clearGalleryConfirmDesc: "Всі виводи галереї будуть видалені назавжди. Це неможливо скасувати.",
    galleryName: "Галерея",
    clearBtn: "Очистити",
    resetAllLabel: "Скинути всі дані",
    resetAllDesc: "Повністю очистити весь AstroCore workspace",
    resetAllConfirmTitle: "Скинути весь workspace?",
    resetAllConfirmDesc: "Всі агенти, чати, провайдери, пам'ять, сховище і галерея будуть видалені. Це неможливо скасувати.",
    resetAllBtn: "Скинути все",
    wholeWorkspaceName: "Весь workspace",
    confirmCancel: "Скасувати",
    confirmConfirm: "Підтвердити",
    aboutTitle: "Про AstroCore",
    versionLabel: "Версія",
    versionValue: "0.1.0 Beta",
    frameworkLabel: "Фреймворк",
    storageLabel: "Зберігання",
    storageValue: "localStorage",
    aiLayerLabel: "AI Layer",
    aiLayerValue: "AstroCore Engine",
  },
  developer: {
    subtitle: "Для Obsidian, VS Code, Browser Extension та майбутніх інтеграцій",
    sectionApiKeys: "API Ключі",
    loadingKeys: "Завантаження…",
    keySingular: "ключ",
    keyPlural: "ключів",
    noKeysYet: "API ключів ще немає",
    noKeysHint: "Натисни «Generate API Key» щоб створити перший ключ",
    activeLabel: "Активний",
    revokedLabel: "Відкликано",
    createdPrefix: "Створено ",
    lastUsedLabel: "Останнє використання: ",
    revokeBtn: "Відкликати",
    neverLabel: "Ніколи",
    sectionPermissions: "Дозволи",
    permissionsDesc: "Нові ключі отримують усі дозволи нижче. Гранульований вибір дозволів під час генерації з'явиться найближчим часом.",
    sectionUsage: "Використання",
    usageRequestsToday: "Запити сьогодні",
    usageRequestsMonth: "Запити цього місяця",
    usageLastRequest: "Останній запит",
    usageCurrentPlan: "Поточний план",
    sectionSecurity: "Безпека",
    securityBold: "API ключі — це секрет.",
    securityRest: " Не передавай їх нікому і не публікуй у відкритих репозиторіях. Якщо ключ скомпрометований — одразу відкличи його тут. Ми не зберігаємо ключі у відкритому вигляді.",
    modalNewKeyTitle: "Новий API ключ",
    modalNewKeyLabel: "Назва ключа",
    modalNewKeyPlaceholder: "напр. Obsidian Plugin",
    modalNewKeyNameError: "Введи назву ключа.",
    modalCreateError: "Не вдалося створити ключ.",
    modalCreating: "Створення…",
    modalCreateBtn: "Створити ключ",
    modalKeyCreatedTitle: "Ключ створено",
    modalRevealWarningPrefix: "Цей ключ показується ",
    modalRevealWarningStrong: "лише один раз",
    modalRevealWarningSuffix: ". Скопіюй і збережи його зараз — повторно побачити повний ключ буде неможливо.",
    modalDoneBtn: "Готово, я зберіг ключ",
    loadKeysError: "Не вдалося завантажити ключі.",
    loadKeysErrorGeneric: "Помилка завантаження ключів.",
    revokeConfirm: "Відкликати цей ключ? Це незворотно.",
    revokeError: "Не вдалося відкликати ключ.",
    revokeSuccessToast: "Ключ відкликано.",
    serverError: "Помилка сервера.",
  },
  apiErrors: {
    unauthorized: "Не авторизовано",
    contentRequired: "Поле content є обов'язковим.",
    untitled: "Без назви",
    memorySaveFailed: "Не вдалося зберегти в Memory.",
    vaultSaveFailed: "Не вдалося зберегти в Vault.",
    gallerySaveFailed: "Не вдалося зберегти в Галерею.",
    nameRequired: "Поле 'name' є обов'язковим.",
    keyIdRequired: "keyId є обов'язковим.",
    keyNotFoundOrForbidden: "Ключ не знайдено, вже відкликаний, або не належить вам.",
  },
  account: {
    title: "Акаунт",
    edit: "Змінити",
    logoutTitle: "Вийти з акаунта?",
    logoutDesc: "Ви будете розлоговані з AstroCore. Локальні дані збережуться в браузері.",
    signOut: "Вийти",
    operatorFallback: "Оператор",
    emailNotSet: "Email не вказано",
    activeBadge: "● Активний",
    operatorTag: "AstroCore Operator",
    supabaseAuthTag: "Supabase Auth",
    savedIndicator: "Збережено",
    profileCard: "Профіль оператора",
    nameLabel: "Ім'я / Псевдонім",
    emailLabel: "Email",
    accountInfoCard: "Інформація акаунта",
    userId: "User ID",
    providerLabel: "Провайдер",
    emailPasswordProvider: "Email / Password",
    securityCard: "Безпека",
    passwordLabel: "Пароль",
    supabaseNotConfigured: "Supabase не налаштовано. Аутентифікація відключена. Дані зберігаються локально в браузері.",
    dataStorageTitle: "Сховище даних",
    dataStorageDesc: "Всі дані зберігаються в localStorage вашого браузера",
    secureBadge: "Безпечно",
    quickAccessCard: "Швидкий доступ",
    quickProvidersDesc: "API ключі та підключені моделі",
    quickAgentsDesc: "Керування AI агентами",
    quickSettingsDesc: "Workspace та системні параметри",
    dangerZoneTitle: "Вийти з акаунта",
    dangerZoneDesc: "Локальні дані залишаться в браузері після виходу.",
  },
  agentDetail: {
    allAgents: "Всі агенти",
    newChat: "Новий чат",
    settingsCard: "Налаштування агента",
    edit: "Редагувати",
    avatarColor: "Колір аватара",
    nameField: "Назва",
    nameRequired: "Назва *",
    description: "Опис",
    descPlaceholder: "Коротко — що вміє цей агент",
    provider: "Провайдер",
    providerRequired: "Провайдер *",
    noProviderText: "Немає провайдерів.",
    addApiKeyLink: "Додайте API ключ",
    notSelected: "не вибрано",
    systemPrompt: "Системний промпт",
    systemPromptPlaceholder: "Ти — досвідчений AI агент. Відповідай чітко і по суті...",
    systemPromptHint: "Визначає поведінку агента. Зміни застосовуються до нових сесій.",
    changesSaved: "Зміни збережено",
    saving: "Зберігаємо...",
    saveChanges: "Зберегти зміни",
    nameEmptyError: "Назва не може бути порожньою",
    modelLabel: "Модель",
    sessionsLabel: "Сесій",
    sessionsSuffix: "чатів",
    providerNotFound: "Не знайдено",
    chatSessions: "Чат-сесії",
    noSessionsYet: "Чат-сесій ще немає",
    noSessionsHint: "Натисніть «Новий чат» вгорі щоб розпочати",
    youPrefix: "Ви: ",
    aiPrefix: "AI: ",
    emptySession: "Порожня сесія",
    deleteSessionConfirm: "Видалити цю сесію?",
    dangerZoneCard: "Небезпечна зона",
    deleteAgentTitle: "Видалити агента",
    deleteAgentHint: "Агент буде видалений назавжди. Чат-сесії залишаться.",
    delete: "Видалити",
    confirmDeleteHint: "Для підтвердження введіть назву агента:",
    confirmDeletePlaceholder: "Введіть назву...",
    confirmDelete: "Підтвердити видалення",
    agentNotFound: "Агента не знайдено",
    agentNotFoundHint: "Можливо, він був видалений",
    backToAgents: "Повернутись до агентів",
    skills: "Скіли",
    tools: "Інструменти",
    knowledge: "Знання",
    chatWithPrefix: "Чат з ",
    timeJustNow: "щойно",
    timeMinAgo: "хв тому",
    timeHourAgo: "год тому",
    timeYesterday: "вчора",
    timeDaysAgo: "д тому",
  },
  agents: {
    title: "Агенти",
    subtitle: "Workspace Agents · AI Agent Layer · ваші персональні AI помічники",
    activeCountSuffix: "активних",
    newAgentBtn: "Новий агент",
    addApiKeyLink: "Додайте API ключ",
    totalAgents: "Всього агентів",
    activeSessions: "Активні сесії",
    providers: "Провайдери",
    noAgentsYet: "Агентів ще немає",
    noAgentsHint: "Створіть першого AI агента. Оберіть готовий шаблон або налаштуйте з нуля.",
    createAgent: "Створити агента",
    addAgentTile: "Додати агента",
    providerNotFound: "Провайдер не знайдено",
    sessionsSuffix: "сесій",
    startChat: "Розпочати чат",
    newAgentModalTitle: "Новий агент",
    templatesLabel: "Шаблони",
    agentTemplatesLabel: "Шаблони агентів",
    skip: "Пропустити →",
    templateAppliedPrefix: 'Шаблон "',
    templateAppliedSuffix: '" застосовано — можете відредагувати нижче',
    nameField: "Назва",
    nameRequired: "Назва *",
    namePlaceholder: "Копірайтер, Аналітик, SEO...",
    description: "Опис",
    descPlaceholder: "Коротко — що вміє цей агент",
    providerRequired: "Провайдер *",
    providerFirstAddKeyPrefix: "Спочатку додайте API ключ у",
    providersLinkLabel: "Провайдерах",
    systemPrompt: "Системний промпт",
    systemPromptPlaceholder: "Ти — досвідчений AI агент. Відповідай чітко і по суті...",
    nameEmptyError: "Введіть назву агента",
    providerEmptyError: "Оберіть провайдера",
    unauthorizedError: "Не авторизовано",
    genericError: "Помилка",
    cancel: "Скасувати",
    create: "Створити агента",
    creating: "Створюємо...",
    deleteConfirmPrefix: 'Видалити агента "',
    deleteConfirmSuffix: '"?',
    categoryAll: "Всі",
    chatWithPrefix: "Чат з ",
  },
  skillCategories: {
    SEO: "SEO",
    SMM: "SMM",
    Sales: "Продажі",
    Affiliate: "Афіліейт",
    Content: "Контент",
    Support: "Підтримка",
    Analyst: "Аналітика",
    "Media Buyer": "Медіабаїнг",
    Strategy: "Стратегія",
    Product: "Продукт",
  },
  chat: {
    renameChat: "Перейменувати чат",
    cancel: "Скасувати",
    saving: "Зберігаємо...",
    save: "Зберегти",
    newChat: "Новий чат",
    noApiKeys: "Немає API ключів. ",
    add: "Додати",
    noAgents: "Немає агентів",
    createAgent: "Створити агента",
    chooseAgent: "Оберіть агента",
    providerNotFound: "Провайдер не знайдено",
    creating: "Створюємо...",
    chatWithPrefix: "Чат з ",
    chooseAgentBtn: "Оберіть агента",
    rename: "Перейменувати",
    delete: "Видалити",
    justNow: "щойно",
    minAgo: "хв",
    hourAgo: "год",
    yesterday: "вчора",
    daysAgo: "д",
    title: "Чати",
    subtitle: "AI Conversations · всі розмови з агентами",
    sessionsSuffix: "сесій",
    loadingLabel: "Завантаження",
    noChatsYet: "Чатів ще немає",
    noChatsHint: "Оберіть агента і почніть розмову.",
    createNewChat: "Створити новий чат",
    totalSessions: "Всього сесій",
    agentsLabel: "Агентів",
    messagesLabel: "Повідомлень",
    searchPlaceholder: "Пошук чатів...",
    agentFilterLabel: "Агент",
    providerFilterLabel: "Провайдер",
    periodLabel: "Період",
    periodToday: "Сьогодні",
    periodWeek: "7 днів",
    periodMonth: "30 днів",
    sortNewest: "Новіші",
    sortOldest: "Старіші",
    sortByTitle: "За назвою",
    clear: "Очистити",
    agentsColonLabel: "агенти:",
    nothingFound: "Нічого не знайдено",
    clearFilters: "Очистити фільтри",
    sessionSingular: "сесія",
    sessionFew: "сесії",
    sessionMany: "сесій",
    filtered: "відфільтровано",
    deleteSessionConfirm: "Видалити цю сесію?",
  },
  chatSession: {
    copy: "Копіювати",
    saveToVault: "Зберегти у Сховище",
    savingEllipsis: "Зберігаємо…",
    saved: "Збережено",
    errorLabel: "Помилка",
    vault: "Сховище",
    saveToGallery: "Зберегти у Галерею",
    gallery: "Галерея",
    saveToMemory: "Зберегти у Пам'ять",
    memory: "Пам'ять",
    memoryChatTitleFallback: "Пам'ять чату",
    vaultSaveError: "Не вдалося зберегти в Сховище.",
    gallerySaveError: "Не вдалося зберегти в Галерею.",
    memorySaveError: "Не вдалося зберегти в Пам'ять.",
    serverError: "Помилка сервера.",
    aiReplyFallback: "AI відповідь",
    sessionNotFound: "Сесію не знайдено",
    sessionNotFoundHint: "Можливо, її було видалено",
    backToAllChats: "До всіх чатів",
    newChatFallback: "Новий чат",
    chatWithPrefix: "Чат з ",
    startConversationHint: "Напишіть повідомлення щоб розпочати розмову з AI агентом.",
    suggestion1: "Привіт! Хто ти?",
    suggestion2: "Що ти вмієш?",
    suggestion3: "Допоможи мені",
    aiCoreOnline: "AI Core Online",
    providerConnected: "Provider Connected",
    memoryLayer: "Memory Layer",
    webMode: "Web mode",
    noProviderConnected: "Немає підключеного провайдера.",
    webModeAnthropicOnlyNote: "Web mode зі справжнім пошуком поки що працює лише з провайдером Anthropic Claude.",
    configure: "Налаштувати",
    micNotSupported: "Голосове введення не підтримується у цьому браузері.",
    listening: "Слухаю...",
    listeningPlaceholder: "Слухаю... говоріть зараз",
    aiRespondingPlaceholder: "AI відповідає...",
    messagePlaceholder: "Напишіть повідомлення...",
    actions: "Дії",
    attachFile: "Прикріпити файл",
    webModeOn: "Web mode увімкнено",
    quickActions: "Швидкі дії",
    stopRecording: "Зупинити запис",
    voiceInput: "Голосовий ввід",
    send: "Надіслати (Enter)",
    hint: "Enter — надіслати · Shift+Enter — рядок · 📎 — файли · 🌐 — web mode · 🎤 — голос",
    fileLabel: "Файл",
    attachedFileLabel: "Прикріплений файл",
    providerNotFoundError: "Провайдер для цього агента не знайдений. Перевірте API ключі у розділі Провайдери.",
    noReply: "Немає відповіді",
    sendError: "Помилка: не вдалося отримати відповідь. Перевірте API ключ у Провайдерах.",
    quickAction1: "Підсумуй коротко",
    quickAction2: "Зроби план",
    quickAction3: "Перепиши професійно",
    quickAction4: "Дай ідеї",
  },
  integrations: {
    title: "Інтеграції",
    subtitle: "Підключай інструменти, розширюй можливості та працюй без обмежень.",
    help: "Довідка",
    addIntegration: "Додати інтеграцію",
    checkingStatus: "Перевіряємо статус…",
    connected: "Підключено",
    notConnected: "Не підключено",
    obsidianDescConnected: "Плагін активний і готовий до роботи.",
    obsidianDescDisconnected: "AstroCore прямо в Obsidian — запитуй AI, переписуй, підсумовуй нотатки і зберігай результати у Vault, не виходячи з редактора.",
    connectionState: "Стан підключення",
    active: "Активно",
    lastUsed: "Останнє використання",
    connectedSince: "Підключено",
    permissions: "Дозволи",
    permissionsOf: "з 5",
    apiKey: "API ключ",
    regenerateKey: "Перегенерувати ключ",
    changeSettings: "Змінити налаштування",
    disconnect: "Відключити",
    connectAstroCore: "Connect AstroCore",
    howToInstall: "Як встановити",
    whatObsidianCanDo: "Що може Obsidian інтеграція",
    endpointLabel: "Endpoint:",
    integrationWorking: "Інтеграція працює коректно",
    dataExchangeSuccess: "Обмін даними відбувається успішно.",
    checkAgain: "Перевірити знову",
    availableIntegrations: "Доступні інтеграції",
    availableIntegrationsDesc: "Підключай улюблені інструменти та розширюй можливості AstroCore.",
    all: "Усі",
    soon: "Скоро",
    newKeyGenerated: "Новий ключ згенеровано",
    revealKeyWarningPrefix: "Показується ",
    revealKeyWarningStrong: "лише зараз",
    revealKeyWarningSuffix: ". Онови ключ у налаштуваннях плагіна Obsidian — старий ключ уже недійсний.",
    done: "Готово",
    disconnectConfirm: "Відключити Obsidian? Плагін перестане мати доступ до AstroCore, поки не підключиш знову.",
    regenerateConfirm: "Перегенерувати ключ? Старий ключ одразу перестане працювати — онови його в плагіні.",
    neverUsed: "Ще не використовувалась",
    obsidianDesc: "Працюй зі своїми нотатками прямо в Obsidian.",
    vscodeDesc: "Виклик AstroCore прямо з редактора коду.",
    browserDesc: "AstroCore в будь-якій вкладці браузера.",
    raycastDesc: "Швидкий доступ через Raycast launcher.",
    zapierDesc: "Автоматизація з тисячами сервісів через Zapier.",
    n8nDesc: "Self-hosted автоматизація через n8n.",
    makeDesc: "Візуальна автоматизація через Make.",
    catNotes: "Нотатки",
    catDev: "Розробка",
    catProductivity: "Продуктивність",
    catAutomation: "Автоматизація",
    installStep1: "Скачай `_integrations/obsidian` з репозиторію AstroCore.",
    installStep2: "В Obsidian: Settings → Community Plugins → Turn on community plugins.",
    installStep3: "Розпакуй плагін у `<твій vault>/.obsidian/plugins/astrocore/`.",
    installStep4: "Онови список плагінів і увімкни AstroCore AI.",
    cap1: "Запити до AI прямо з нотатки",
    cap2: "Надсилання нотатки/виділення в AstroCore Vault",
    cap3: "Переписування та пояснення виділеного тексту",
    cap4: "Підсумок поточної нотатки одним кліком",
    cap5: "Захищений доступ через персональний API-ключ",
  },
  loginPage: {
    headline1: "AI Operating",
    headline2: "System",
    headline3: "for",
    headline4: "Your Workflow",
    subhead: "Build AI agents, manage knowledge and run multi-model workflows — all in one premium workspace.",
    feature1Title: "AI Agent Layer",
    feature1Desc: "Create intelligent agents with custom personalities and system prompts.",
    feature2Title: "Persistent Memory",
    feature2Desc: "Workspace memory injected into every agent request automatically.",
    feature3Title: "Multi-Provider",
    feature3Desc: "Switch between Claude, GPT-4o, Gemini and custom endpoints freely.",
    feature4Title: "Vault & Gallery",
    feature4Desc: "Save AI outputs, knowledge and generations across all sessions.",
    connectedProviders: "Connected Providers",
    memoryLayerActive: "Memory Layer Active",
    online: "Online",
    title: "Вхід в акаунт",
    subtitle: "Operator Authentication Layer",
    email: "Email",
    password: "Пароль",
    fillFieldsError: "Заповніть email і пароль",
    wrongCredentialsError: "Невірний email або пароль",
    signingIn: "Входимо...",
    signIn: "Увійти в AstroCore",
    securityNote: "Захищено Supabase Auth · Дані шифруються",
    noAccount: "Немає акаунта?",
    signUp: "Зареєструватись",
  },
  registerPage: {
    headline1: "Join the",
    headline2: "AI-First",
    headline3: "Workspace",
    subhead: "Create your AstroCore account and get instant access to a full AI agent workspace with multi-model support.",
    benefit1: "Необмежена кількість AI агентів",
    benefit2: "Персистентна пам'ять для агентів",
    benefit3: "Синхронізація між пристроями",
    benefit4: "Безпечне зберігання API ключів",
    benefit5: "Claude, GPT-4o, Gemini в одному місці",
    supportedProviders: "Supported Providers",
    memoryLayerActive: "Memory Layer Active",
    online: "Online",
    title: "Створити акаунт",
    subtitle: "New Operator Registration",
    nameLabel: "Ім'я",
    namePlaceholder: "Ваше ім'я або псевдонім",
    emailLabel: "Email *",
    passwordLabel: "Пароль *",
    passwordPlaceholder: "Мінімум 6 символів",
    fillFieldsError: "Заповніть email і пароль",
    passwordTooShortError: "Пароль мінімум 6 символів",
    registering: "Реєстрація...",
    join: "Приєднатись до AstroCore",
    securityNote: "Захищено Supabase Auth · Дані синхронізуються між пристроями",
    alreadyHaveAccount: "Вже є акаунт?",
    signIn: "Увійти",
  },
  memory: {
    rename: "Перейменувати",
    enterTitleError: "Введіть назву",
    enterContentError: "Введіть вміст пам'яті",
    notAuthorizedError: "Не авторизовано",
    newEntryTitle: "Новий запис пам'яті",
    layerLabel: "AI Memory Layer",
    nameField: "Назва *",
    namePlaceholder: "Назва контексту або знання...",
    contentField: "Вміст *",
    contentPlaceholder: "Контекст, інформація, інструкції для AI агента...",
    contentHint: "Цей вміст буде автоматично інжектуватись у кожен запит агента.",
    cancel: "Скасувати",
    saving: "Зберігаємо...",
    saveToMemory: "Зберегти в пам'ять",
    saved: "Збережено",
    collapse: "Згорнути",
    expand: "Розгорнути",
    activeContext: "Active Context",
    justNow: "щойно",
    minAgo: "хв тому",
    hourAgo: "год тому",
    yesterday: "вчора",
    daysAgo: "д тому",
    emptyTitle: "Пам'ять порожня",
    emptyDesc: "Додайте контекст, інструкції або знання. Вони будуть автоматично інжектуватись у кожен запит агента.",
    persistentContext: "Persistent Context · Knowledge Engine",
    addMemory: "Додати пам'ять",
    contextActive: "Контекст активний",
    memoryEmpty: "Пам'ять порожня",
    entriesSuffix: "записів",
    title: "Пам'ять",
    subtitle: "AI Memory Layer · Persistent Context · Knowledge Engine",
    injectedIntoAgents: "Інжектується в агентів",
    newMemory: "Нова пам'ять",
    statEntries: "Записів пам'яті",
    statChars: "Символів контексту",
    statInjectedInto: "Інжектується в",
    statAllAgents: "всі агенти",
    howItWorksTitle: "Як це працює",
    howItWorksDesc: "Всі записи пам'яті автоматично інжектуються в системний промпт кожного агента. Це дозволяє агентам знати контекст вашого бізнесу, проекту та правила поведінки.",
    searchPlaceholder: "Пошук в пам'яті...",
    foundOfPrefix: "Знайдено ",
    foundOfMid: " із ",
    foundOfSuffix: " записів",
    nothingFound: "Нічого не знайдено",
    deleteConfirmPrefix: 'Видалити "',
    deleteConfirmSuffix: '"?',
  },
  providers: {
    openaiDesc: "GPT-4o, GPT-4 Turbo та інші моделі OpenAI",
    anthropicDesc: "Claude Opus, Sonnet та Haiku від Anthropic",
    googleDesc: "Gemini 2.0 Flash та Gemini Pro від Google",
    customDesc: "Власний AI провайдер або OpenAI-сумісний endpoint",
    enterApiKeyError: "Введіть API ключ",
    notAuthorizedError: "Не авторизовано",
    connectProviderTitle: "Підключити провайдера",
    apiControlLayer: "API Control Layer",
    providerField: "Провайдер",
    providerNamePlaceholder: "Мій AI провайдер...",
    providerNameField: "Назва провайдера",
    modelField: "Модель",
    apiKeyField: "API Ключ *",
    keysStoredNote: "Ключі зберігаються у захищеній базі даних Supabase і прив'язані до вашого акаунта.",
    cancel: "Скасувати",
    saving: "Зберігаємо...",
    connect: "Підключити",
    active: "Активний",
    disabled: "Вимкнено",
    apiKeyLabel: "API Ключ",
    enable: "Увімкнути",
    disable: "Вимкнути",
    delete: "Видалити",
    deleteConfirmPrefix: 'Видалити провайдера "',
    deleteConfirmSuffix: '"?',
    emptyTitle: "Немає підключених провайдерів",
    emptyDesc: "Підключіть OpenAI, Anthropic, Google Gemini або власний AI провайдер щоб агенти могли відповідати.",
    modelGateway: "API Control Layer · Model Gateway",
    connectProvider: "Підключити провайдера",
    providerGatewayActive: "Provider Gateway Active",
    noActiveProviders: "No Active Providers",
    connectedSuffix: "підключено",
    title: "Провайдери",
    subtitle: "API Control Layer · Model Gateway · підключіть AI моделі до агентів",
    activeSuffix: "активних",
    connectBtn: "Підключити",
    totalProviders: "Всього провайдерів",
    activeLabel: "Активних",
    disabledLabel: "Вимкнених",
    securityNote: "API ключі зберігаються у захищеній базі даних Supabase і прив'язані до вашого акаунта. Дані синхронізуються між пристроями.",
    connectAnother: "Підключити ще одного провайдера",
    webhookUrlField: "Endpoint URL",
    webhookUrlHint: "Базова адреса твого AI-агента, сумісна з OpenAI API (наприклад https://your-agent.example.com/v1).",
    authHeaderField: "Заголовок авторизації (необов'язково)",
    authHeaderHint: "Якщо не заповнено — використовується 'Bearer <API ключ>' за замовчуванням.",
    customHeadersField: "Додаткові заголовки (JSON, необов'язково)",
    customHeadersHint: "Об'єкт рядок→рядок, до 20 полів. Наприклад: { \"X-Org-Id\": \"12345\" }.",
    testConnectionBtn: "Перевірити підключення",
    testing: "Перевіряємо…",
    testSuccess: "Підключення успішне",
    testFailed: "Не вдалося підключитись",
    testMissingFields: "Заповніть Endpoint URL, модель і API ключ перед перевіркою.",
    webhookRequiredError: "Вкажіть Endpoint URL для Custom провайдера.",
    modelRequiredError: "Вкажіть модель.",
    saveFailedError: "Не вдалося зберегти провайдера.",
    statusConnected: "Підключено",
    statusFailed: "Помилка",
    statusUnverified: "Не перевірено",
  },
  vault: {
    enterTitleError: "Введіть назву запису",
    enterContentError: "Введіть вміст запису",
    notAuthorizedError: "Не авторизовано",
    newEntryTitle: "Новий запис",
    knowledgeVaultLabel: "AI Knowledge Vault",
    nameField: "Назва *",
    namePlaceholder: "Назва знання або теми...",
    contentField: "Вміст *",
    contentPlaceholder: "Текст, нотатка, відповідь AI, інформація...",
    tagsField: "Теги",
    tagsPlaceholder: "Додати тег і натиснути Enter...",
    cancel: "Скасувати",
    saving: "Зберігаємо...",
    saveEntry: "Зберегти запис",
    copyContent: "Копіювати вміст",
    copyTitle: "Копіювати назву",
    copied: "Скопійовано",
    downloadMd: "Завантажити .md",
    sendToObsidianTooltip: "Відкриє Obsidian через obsidian://new",
    openingEllipsis: "Відкриваємо…",
    sent: "Відправлено",
    failed: "Не вдалося",
    sendToObsidian: "Send to Obsidian",
    close: "Закрити",
    deleteConfirmPrefix: 'Видалити "',
    deleteConfirmSuffix: '"?',
    emptyTitle: "Сховище порожнє",
    emptyDesc: "Зберігайте знання, відповіді AI, нотатки та будь-яку корисну інформацію.",
    addEntry: "Додати запис",
    knowledgeBase: "AI Knowledge Vault · Knowledge Base",
    title: "Сховище знань",
    subtitle: "AI Knowledge Base · зберігайте і переглядайте знання",
    newEntry: "Новий запис",
    entriesSuffix: "записів",
    statTotal: "Всього записів",
    statUniqueTags: "Унікальних тегів",
    statCharsSaved: "Символів збережено",
    searchPlaceholder: "Пошук по назві та вмісту...",
    all: "Всі",
    foundOfPrefix: "Знайдено ",
    foundOfMid: " із ",
    foundOfSuffix: " записів",
    clear: "Очистити",
    nothingFound: "Нічого не знайдено",
    justNow: "щойно",
    minAgo: "хв тому",
    hourAgo: "год тому",
    yesterday: "вчора",
    daysAgo: "д тому",
    obsidianVaultPrompt: "Введи назву свого Obsidian vault (як він називається у списку vault'ів в Obsidian):",
  },
  forum: {
    title: "Форум",
    subtitle: "Community Layer · обговорення AI в реальному часі",
    categoriesTitle: "Категорії",
    topicsCount: "тем",
    postsCount: "повідомлень",
    newTopic: "Нова тема",
    newTopicTitle: "Створити тему",
    topicTitleField: "Заголовок *",
    topicTitlePlaceholder: "Про що хочете поговорити?",
    topicContentField: "Повідомлення *",
    topicContentPlaceholder: "Опишіть детальніше...",
    categoryField: "Категорія *",
    cancel: "Скасувати",
    publish: "Опублікувати",
    publishing: "Публікуємо...",
    titleRequiredError: "Введіть заголовок теми",
    contentRequiredError: "Введіть текст повідомлення",
    categoryRequiredError: "Оберіть категорію",
    loginToPost: "Увійдіть, щоб писати на форумі",
    loginBtn: "Увійти",
    backToForum: "До форуму",
    backToCategory: "До категорії",
    noTopicsYet: "Тем ще немає",
    noTopicsHint: "Будьте першим, хто почне обговорення в цій категорії.",
    createFirstTopic: "Створити першу тему",
    replyPlaceholder: "Напишіть відповідь...",
    sendReply: "Відповісти",
    sending: "Надсилаємо...",
    noRepliesYet: "Відповідей ще немає",
    noRepliesHint: "Станьте першим, хто відповість.",
    repliesLabel: "відповідей",
    pinnedLabel: "Закріплено",
    lockedLabel: "Закрито",
    lockedNotice: "Цю тему закрито, нові відповіді недоступні.",
    anonymousUser: "Учасник",
    liveIndicator: "Наживо",
    justNow: "щойно",
    minAgo: "хв тому",
    hourAgo: "год тому",
    yesterday: "вчора",
    daysAgo: "д тому",
    loadError: "Не вдалося завантажити дані форуму.",
    postError: "Не вдалося опублікувати. Спробуйте ще раз.",
    deleteConfirm: "Видалити це повідомлення?",
    delete: "Видалити",
    topicsInCategory: "Теми",
    lastActivity: "Остання активність",
    startedBy: "Автор",
  },
  gallery: {
    typeText: "Текст",
    typeCode: "Код",
    typeImage: "Зображ.",
    justNow: "щойно",
    minAgo: "хв",
    hourAgo: "год",
    yesterday: "вчора",
    daysAgo: "д",
    saveOutputTitle: "Зберегти вивід",
    layerLabel: "AI Output Gallery",
    typeOfOutput: "Тип виводу",
    nameField: "Назва *",
    namePlaceholder: "Назва виводу...",
    contentField: "Вміст *",
    contentPlaceholderCode: "// Вставте код...",
    contentPlaceholderImage: "URL зображення або опис...",
    contentPlaceholderText: "Текст виводу AI...",
    enterTitleError: "Введіть назву",
    enterContentError: "Введіть вміст",
    notAuthorizedError: "Не авторизовано",
    cancel: "Скасувати",
    saving: "Зберігаємо...",
    save: "Зберегти",
    deleteConfirmPrefix: 'Видалити "',
    deleteConfirmSuffix: '"?',
    aiOutputLabel: "AI вивід",
    emptyTitle: "Галерея порожня",
    emptyDesc: "Зберігайте найкращі виводи AI — тексти, код та зображення в одному місці.",
    addOutput: "Зберегти вивід",
    savedGenerations: "AI Output Gallery · Saved Generations",
    title: "Галерея",
    subtitle: "AI Saved Generations · найкращі виводи в одному місці",
    outputsSuffix: "виводів",
    totalOutputs: "Всього виводів",
    textsLabel: "Текстів",
    codesLabel: "Кодів",
    imagesLabel: "Зображень",
    searchPlaceholder: "Пошук по галереї...",
    filterAll: "Всі",
    foundOfPrefix: "Знайдено ",
    foundOfMid: " із ",
    clear: "Очистити",
    nothingFound: "Нічого не знайдено",
  },
}

const en: typeof uk = {
  common: {
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
  },
  sidebar: {
    center: "Center",
    chat: "Chat",
    agents: "Agents",
    memory: "Memory",
    vault: "Vault",
    gallery: "Gallery",
    forum: "Forum",
    integrations: "Integrations",
    settings: "Settings",
    providers: "Providers",
    back: "Back",
    contact: "Contact",
    contactSubtitle: "Message us on your preferred channel",
    telegramSubtitle: "Quick reply",
    yourPlan: "Your plan",
    upgrade: "Upgrade",
    account: "Account",
    signOut: "Sign out",
  },
  dashboard: {
    onlineBadge: "AI CORE — ONLINE",
    greetingMorning: "Good morning",
    greetingDay: "Good afternoon",
    greetingEvening: "Good evening",
    newAgent: "New agent",
    openChat: "Open chat",
    addApiKey: "Add API key",
    addApiKeyBanner: "Add an API key so agents can respond",
    statAgents: "Agents",
    statAgentsSub: "active",
    statSessions: "Sessions",
    statSessionsSub: "conversations",
    statProviders: "Providers",
    statProvidersSub: "connected",
    statVault: "Vault",
    statVaultSub: "entries",
    statMemory: "Memory",
    statMemorySub: "entries",
    statGallery: "Gallery",
    statGallerySub: "outputs",
    agentsPanel: "Agents",
    allAgents: "All agents",
    noAgents: "No agents yet",
    createAgent: "Create agent",
    createNewAgent: "Create a new agent",
    recentChats: "Recent chats",
    allSessions: "All sessions",
    noSessions: "No sessions yet",
    newChat: "New chat",
    openNewChat: "Open a new chat",
    knowledgeVault: "Knowledge vault",
    open: "Open",
    emptyVault: "Vault is empty",
    providersPanel: "Providers",
    manage: "Manage",
    noProviders: "No providers",
    active: "Active",
    inactive: "Disabled",
    quickActions: "Quick actions",
    recentActivity: "Recent activity",
    activityNewAgent: "Created a new agent",
    activityNewSession: "Started a new session",
    activitySavedVault: "Saved an entry",
  },
  login: {
    title: "Login",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    signIn: "Sign in",
    noAccount: "Don't have an account?",
    createOne: "Sign up",
  },
  register: {
    title: "Create account",
    name: "Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
    createAccount: "Create account",
  },
  settings: {
    language: "Language",
    languageDesc: "Choose the AstroCore interface language.",
    subtitleTagline: "AI Operating Layer · Workspace Settings · System Control",
    statAgents: "agents",
    statChats: "chats",
    statProviders: "providers",
    statVault: "in vault",
    statGallery: "in gallery",
    clearedSuffix: "cleared successfully",
    sectionsTitle: "Sections",
    accountDesc: "Profile, avatar, personal information",
    providersDesc: "API keys, connected AI models",
    memoryDesc: "Context and knowledge injected into agents",
    vaultDesc: "Saved knowledge and notes",
    galleryDesc: "Saved AI outputs",
    devCenterLabel: "Developer Center",
    devCenterDesc: "API Keys, Webhooks, Integrations and Developer tools.",
    systemStatusTitle: "System Status",
    aiCoreLabel: "AI Core",
    onlineLabel: "Online",
    localStorageLabel: "localStorage",
    availableLabel: "Available",
    providersStatusLabel: "Providers",
    connectedSuffix: "connected",
    noneLabel: "None",
    activeAgentsLabel: "Active agents",
    agentsCountSuffix: "agents",
    securityTitle: "Security & Privacy",
    securityDesc: "All data is stored locally in your browser. API keys, agents, chats, and all memory live only in your localStorage. No external servers.",
    apiKeysLabel: "API keys",
    apiKeysDesc: "Go to provider settings",
    dataManagementTitle: "Data Management",
    clearAgentsLabel: "Clear agents",
    clearAgentsDescPrefix: "Delete all ",
    clearAgentsDescSuffix: " agents permanently",
    clearAgentsConfirmTitle: "Clear agents?",
    clearAgentsConfirmDesc: "All agents will be permanently deleted. This cannot be undone.",
    agentsName: "Agents",
    clearChatsLabel: "Clear chats",
    clearChatsDescPrefix: "Delete all ",
    clearChatsDescSuffix: " sessions permanently",
    clearChatsConfirmTitle: "Clear chats?",
    clearChatsConfirmDesc: "All chats will be permanently deleted. This cannot be undone.",
    chatsName: "Chats",
    clearMemoryLabel: "Clear memory",
    clearMemoryDesc: "Delete all context and knowledge",
    clearMemoryConfirmTitle: "Clear memory?",
    clearMemoryConfirmDesc: "All context and knowledge will be permanently deleted. This cannot be undone.",
    memoryName: "Memory",
    clearVaultLabel: "Clear vault",
    clearVaultDescPrefix: "Delete all ",
    clearVaultDescSuffix: " entries",
    clearVaultConfirmTitle: "Clear vault?",
    clearVaultConfirmDesc: "All vault entries will be permanently deleted. This cannot be undone.",
    vaultName: "Vault",
    clearGalleryLabel: "Clear gallery",
    clearGalleryDescPrefix: "Delete all ",
    clearGalleryDescSuffix: " outputs",
    clearGalleryConfirmTitle: "Clear gallery?",
    clearGalleryConfirmDesc: "All gallery outputs will be permanently deleted. This cannot be undone.",
    galleryName: "Gallery",
    clearBtn: "Clear",
    resetAllLabel: "Reset all data",
    resetAllDesc: "Fully clear the entire AstroCore workspace",
    resetAllConfirmTitle: "Reset the whole workspace?",
    resetAllConfirmDesc: "All agents, chats, providers, memory, vault, and gallery will be deleted. This cannot be undone.",
    resetAllBtn: "Reset everything",
    wholeWorkspaceName: "Entire workspace",
    confirmCancel: "Cancel",
    confirmConfirm: "Confirm",
    aboutTitle: "About AstroCore",
    versionLabel: "Version",
    versionValue: "0.1.0 Beta",
    frameworkLabel: "Framework",
    storageLabel: "Storage",
    storageValue: "localStorage",
    aiLayerLabel: "AI Layer",
    aiLayerValue: "AstroCore Engine",
  },
  developer: {
    subtitle: "For Obsidian, VS Code, Browser Extension, and future integrations",
    sectionApiKeys: "API Keys",
    loadingKeys: "Loading…",
    keySingular: "key",
    keyPlural: "keys",
    noKeysYet: "No API keys yet",
    noKeysHint: "Click \"Generate API Key\" to create your first key",
    activeLabel: "Active",
    revokedLabel: "Revoked",
    createdPrefix: "Created ",
    lastUsedLabel: "Last used: ",
    revokeBtn: "Revoke",
    neverLabel: "Never",
    sectionPermissions: "Permissions",
    permissionsDesc: "New keys receive all the permissions below. Granular permission selection at generation time is coming soon.",
    sectionUsage: "Usage",
    usageRequestsToday: "Requests today",
    usageRequestsMonth: "Requests this month",
    usageLastRequest: "Last request",
    usageCurrentPlan: "Current plan",
    sectionSecurity: "Security",
    securityBold: "API keys are a secret.",
    securityRest: " Don't share them with anyone or publish them in public repositories. If a key is compromised, revoke it here immediately. We never store keys in plaintext.",
    modalNewKeyTitle: "New API key",
    modalNewKeyLabel: "Key name",
    modalNewKeyPlaceholder: "e.g. Obsidian Plugin",
    modalNewKeyNameError: "Enter a key name.",
    modalCreateError: "Couldn't create the key.",
    modalCreating: "Creating…",
    modalCreateBtn: "Create key",
    modalKeyCreatedTitle: "Key created",
    modalRevealWarningPrefix: "This key is shown ",
    modalRevealWarningStrong: "only once",
    modalRevealWarningSuffix: ". Copy and save it now — you won't be able to see the full key again.",
    modalDoneBtn: "Done, I saved the key",
    loadKeysError: "Couldn't load keys.",
    loadKeysErrorGeneric: "Error loading keys.",
    revokeConfirm: "Revoke this key? This can't be undone.",
    revokeError: "Couldn't revoke the key.",
    revokeSuccessToast: "Key revoked.",
    serverError: "Server error.",
  },
  apiErrors: {
    unauthorized: "Not authorized",
    contentRequired: "The 'content' field is required.",
    untitled: "Untitled",
    memorySaveFailed: "Couldn't save to Memory.",
    vaultSaveFailed: "Couldn't save to Vault.",
    gallerySaveFailed: "Couldn't save to Gallery.",
    nameRequired: "The 'name' field is required.",
    keyIdRequired: "keyId is required.",
    keyNotFoundOrForbidden: "Key not found, already revoked, or doesn't belong to you.",
  },
  account: {
    title: "Account",
    edit: "Edit",
    logoutTitle: "Sign out of your account?",
    logoutDesc: "You'll be signed out of AstroCore. Local data will remain in your browser.",
    signOut: "Sign out",
    operatorFallback: "Operator",
    emailNotSet: "Email not set",
    activeBadge: "● Active",
    operatorTag: "AstroCore Operator",
    supabaseAuthTag: "Supabase Auth",
    savedIndicator: "Saved",
    profileCard: "Operator profile",
    nameLabel: "Name / Alias",
    emailLabel: "Email",
    accountInfoCard: "Account information",
    userId: "User ID",
    providerLabel: "Provider",
    emailPasswordProvider: "Email / Password",
    securityCard: "Security",
    passwordLabel: "Password",
    supabaseNotConfigured: "Supabase is not configured. Authentication is disabled. Data is stored locally in your browser.",
    dataStorageTitle: "Data storage",
    dataStorageDesc: "All data is stored in your browser's localStorage",
    secureBadge: "Secure",
    quickAccessCard: "Quick access",
    quickProvidersDesc: "API keys and connected models",
    quickAgentsDesc: "Manage your AI agents",
    quickSettingsDesc: "Workspace and system settings",
    dangerZoneTitle: "Sign out of account",
    dangerZoneDesc: "Local data will remain in the browser after signing out.",
  },
  agentDetail: {
    allAgents: "All agents",
    newChat: "New chat",
    settingsCard: "Agent settings",
    edit: "Edit",
    avatarColor: "Avatar color",
    nameField: "Name",
    nameRequired: "Name *",
    description: "Description",
    descPlaceholder: "Briefly — what this agent can do",
    provider: "Provider",
    providerRequired: "Provider *",
    noProviderText: "No providers.",
    addApiKeyLink: "Add an API key",
    notSelected: "not selected",
    systemPrompt: "System prompt",
    systemPromptPlaceholder: "You are an experienced AI agent. Respond clearly and to the point...",
    systemPromptHint: "Defines the agent's behavior. Changes apply to new sessions.",
    changesSaved: "Changes saved",
    saving: "Saving...",
    saveChanges: "Save changes",
    nameEmptyError: "Name cannot be empty",
    modelLabel: "Model",
    sessionsLabel: "Sessions",
    sessionsSuffix: "chats",
    providerNotFound: "Not found",
    chatSessions: "Chat sessions",
    noSessionsYet: "No chat sessions yet",
    noSessionsHint: "Click “New chat” above to get started",
    youPrefix: "You: ",
    aiPrefix: "AI: ",
    emptySession: "Empty session",
    deleteSessionConfirm: "Delete this session?",
    dangerZoneCard: "Danger zone",
    deleteAgentTitle: "Delete agent",
    deleteAgentHint: "The agent will be permanently deleted. Chat sessions will remain.",
    delete: "Delete",
    confirmDeleteHint: "To confirm, type the agent's name:",
    confirmDeletePlaceholder: "Type the name...",
    confirmDelete: "Confirm deletion",
    agentNotFound: "Agent not found",
    agentNotFoundHint: "It may have been deleted",
    backToAgents: "Back to agents",
    skills: "Skills",
    tools: "Tools",
    knowledge: "Knowledge",
    chatWithPrefix: "Chat with ",
    timeJustNow: "just now",
    timeMinAgo: "min ago",
    timeHourAgo: "h ago",
    timeYesterday: "yesterday",
    timeDaysAgo: "d ago",
  },
  agents: {
    title: "Agents",
    subtitle: "Workspace Agents · AI Agent Layer · your personal AI assistants",
    activeCountSuffix: "active",
    newAgentBtn: "New agent",
    addApiKeyLink: "Add an API key",
    totalAgents: "Total agents",
    activeSessions: "Active sessions",
    providers: "Providers",
    noAgentsYet: "No agents yet",
    noAgentsHint: "Create your first AI agent. Choose a ready template or configure one from scratch.",
    createAgent: "Create agent",
    addAgentTile: "Add agent",
    providerNotFound: "Provider not found",
    sessionsSuffix: "sessions",
    startChat: "Start chat",
    newAgentModalTitle: "New agent",
    templatesLabel: "Templates",
    agentTemplatesLabel: "Agent templates",
    skip: "Skip →",
    templateAppliedPrefix: 'Template "',
    templateAppliedSuffix: '" applied — you can edit it below',
    nameField: "Name",
    nameRequired: "Name *",
    namePlaceholder: "Copywriter, Analyst, SEO...",
    description: "Description",
    descPlaceholder: "Briefly — what this agent can do",
    providerRequired: "Provider *",
    providerFirstAddKeyPrefix: "First add an API key in",
    providersLinkLabel: "Providers",
    systemPrompt: "System prompt",
    systemPromptPlaceholder: "You are an experienced AI agent. Respond clearly and to the point...",
    nameEmptyError: "Enter an agent name",
    providerEmptyError: "Select a provider",
    unauthorizedError: "Not authorized",
    genericError: "Error",
    cancel: "Cancel",
    create: "Create agent",
    creating: "Creating...",
    deleteConfirmPrefix: 'Delete agent "',
    deleteConfirmSuffix: '"?',
    categoryAll: "All",
    chatWithPrefix: "Chat with ",
  },
  skillCategories: {
    SEO: "SEO",
    SMM: "SMM",
    Sales: "Sales",
    Affiliate: "Affiliate",
    Content: "Content",
    Support: "Support",
    Analyst: "Analyst",
    "Media Buyer": "Media Buyer",
    Strategy: "Strategy",
    Product: "Product",
  },
  chat: {
    renameChat: "Rename chat",
    cancel: "Cancel",
    saving: "Saving...",
    save: "Save",
    newChat: "New chat",
    noApiKeys: "No API keys. ",
    add: "Add",
    noAgents: "No agents",
    createAgent: "Create agent",
    chooseAgent: "Choose an agent",
    providerNotFound: "Provider not found",
    creating: "Creating...",
    chatWithPrefix: "Chat with ",
    chooseAgentBtn: "Choose an agent",
    rename: "Rename",
    delete: "Delete",
    justNow: "just now",
    minAgo: "min",
    hourAgo: "h",
    yesterday: "yesterday",
    daysAgo: "d",
    title: "Chats",
    subtitle: "AI Conversations · all conversations with agents",
    sessionsSuffix: "sessions",
    loadingLabel: "Loading",
    noChatsYet: "No chats yet",
    noChatsHint: "Choose an agent and start a conversation.",
    createNewChat: "Create new chat",
    totalSessions: "Total sessions",
    agentsLabel: "Agents",
    messagesLabel: "Messages",
    searchPlaceholder: "Search chats...",
    agentFilterLabel: "Agent",
    providerFilterLabel: "Provider",
    periodLabel: "Period",
    periodToday: "Today",
    periodWeek: "7 days",
    periodMonth: "30 days",
    sortNewest: "Newest",
    sortOldest: "Oldest",
    sortByTitle: "By title",
    clear: "Clear",
    agentsColonLabel: "agents:",
    nothingFound: "Nothing found",
    clearFilters: "Clear filters",
    sessionSingular: "session",
    sessionFew: "sessions",
    sessionMany: "sessions",
    filtered: "filtered",
    deleteSessionConfirm: "Delete this session?",
  },
  chatSession: {
    copy: "Copy",
    saveToVault: "Save to Vault",
    savingEllipsis: "Saving…",
    saved: "Saved",
    errorLabel: "Error",
    vault: "Vault",
    saveToGallery: "Save to Gallery",
    gallery: "Gallery",
    saveToMemory: "Save to Memory",
    memory: "Memory",
    memoryChatTitleFallback: "Chat memory",
    vaultSaveError: "Couldn't save to Vault.",
    gallerySaveError: "Couldn't save to Gallery.",
    memorySaveError: "Couldn't save to Memory.",
    serverError: "Server error.",
    aiReplyFallback: "AI reply",
    sessionNotFound: "Session not found",
    sessionNotFoundHint: "It may have been deleted",
    backToAllChats: "Back to all chats",
    newChatFallback: "New chat",
    chatWithPrefix: "Chat with ",
    startConversationHint: "Write a message to start a conversation with the AI agent.",
    suggestion1: "Hi! Who are you?",
    suggestion2: "What can you do?",
    suggestion3: "Help me out",
    aiCoreOnline: "AI Core Online",
    providerConnected: "Provider Connected",
    memoryLayer: "Memory Layer",
    webMode: "Web mode",
    noProviderConnected: "No provider connected.",
    webModeAnthropicOnlyNote: "Web mode with real search currently only works with the Anthropic Claude provider.",
    configure: "Configure",
    micNotSupported: "Voice input isn't supported in this browser.",
    listening: "Listening...",
    listeningPlaceholder: "Listening... speak now",
    aiRespondingPlaceholder: "AI is responding...",
    messagePlaceholder: "Write a message...",
    actions: "Actions",
    attachFile: "Attach file",
    webModeOn: "Web mode is on",
    quickActions: "Quick actions",
    stopRecording: "Stop recording",
    voiceInput: "Voice input",
    send: "Send (Enter)",
    hint: "Enter — send · Shift+Enter — new line · 📎 — files · 🌐 — web mode · 🎤 — voice",
    fileLabel: "File",
    attachedFileLabel: "Attached file",
    providerNotFoundError: "No provider found for this agent. Check your API keys under Providers.",
    noReply: "No reply",
    sendError: "Error: couldn't get a reply. Check your API key under Providers.",
    quickAction1: "Summarize briefly",
    quickAction2: "Make a plan",
    quickAction3: "Rewrite professionally",
    quickAction4: "Give me ideas",
  },
  integrations: {
    title: "Integrations",
    subtitle: "Connect tools, extend capabilities, and work without limits.",
    help: "Help",
    addIntegration: "Add integration",
    checkingStatus: "Checking status…",
    connected: "Connected",
    notConnected: "Not connected",
    obsidianDescConnected: "The plugin is active and ready to go.",
    obsidianDescDisconnected: "AstroCore right inside Obsidian — ask the AI, rewrite, summarize notes, and save results to the Vault without leaving your editor.",
    connectionState: "Connection status",
    active: "Active",
    lastUsed: "Last used",
    connectedSince: "Connected",
    permissions: "Permissions",
    permissionsOf: "of 5",
    apiKey: "API key",
    regenerateKey: "Regenerate key",
    changeSettings: "Change settings",
    disconnect: "Disconnect",
    connectAstroCore: "Connect AstroCore",
    howToInstall: "How to install",
    whatObsidianCanDo: "What the Obsidian integration can do",
    endpointLabel: "Endpoint:",
    integrationWorking: "Integration is working correctly",
    dataExchangeSuccess: "Data is being exchanged successfully.",
    checkAgain: "Check again",
    availableIntegrations: "Available integrations",
    availableIntegrationsDesc: "Connect your favorite tools and extend AstroCore's capabilities.",
    all: "All",
    soon: "Soon",
    newKeyGenerated: "New key generated",
    revealKeyWarningPrefix: "Shown ",
    revealKeyWarningStrong: "only now",
    revealKeyWarningSuffix: ". Update the key in the Obsidian plugin settings — the old key is no longer valid.",
    done: "Done",
    disconnectConfirm: "Disconnect Obsidian? The plugin will lose access to AstroCore until you connect it again.",
    regenerateConfirm: "Regenerate the key? The old key will stop working immediately — update it in the plugin.",
    neverUsed: "Not used yet",
    obsidianDesc: "Work with your notes right inside Obsidian.",
    vscodeDesc: "Call AstroCore right from your code editor.",
    browserDesc: "AstroCore in any browser tab.",
    raycastDesc: "Quick access through the Raycast launcher.",
    zapierDesc: "Automate with thousands of services via Zapier.",
    n8nDesc: "Self-hosted automation via n8n.",
    makeDesc: "Visual automation via Make.",
    catNotes: "Notes",
    catDev: "Development",
    catProductivity: "Productivity",
    catAutomation: "Automation",
    installStep1: "Download `_integrations/obsidian` from the AstroCore repository.",
    installStep2: "In Obsidian: Settings → Community Plugins → Turn on community plugins.",
    installStep3: "Unzip the plugin into `<your vault>/.obsidian/plugins/astrocore/`.",
    installStep4: "Refresh the plugin list and enable AstroCore AI.",
    cap1: "Query the AI right from a note",
    cap2: "Send a note/selection to the AstroCore Vault",
    cap3: "Rewrite and explain selected text",
    cap4: "Summarize the current note with one click",
    cap5: "Secure access via a personal API key",
  },
  loginPage: {
    headline1: "AI Operating",
    headline2: "System",
    headline3: "for",
    headline4: "Your Workflow",
    subhead: "Build AI agents, manage knowledge and run multi-model workflows — all in one premium workspace.",
    feature1Title: "AI Agent Layer",
    feature1Desc: "Create intelligent agents with custom personalities and system prompts.",
    feature2Title: "Persistent Memory",
    feature2Desc: "Workspace memory injected into every agent request automatically.",
    feature3Title: "Multi-Provider",
    feature3Desc: "Switch between Claude, GPT-4o, Gemini and custom endpoints freely.",
    feature4Title: "Vault & Gallery",
    feature4Desc: "Save AI outputs, knowledge and generations across all sessions.",
    connectedProviders: "Connected Providers",
    memoryLayerActive: "Memory Layer Active",
    online: "Online",
    title: "Sign in to your account",
    subtitle: "Operator Authentication Layer",
    email: "Email",
    password: "Password",
    fillFieldsError: "Fill in email and password",
    wrongCredentialsError: "Incorrect email or password",
    signingIn: "Signing in...",
    signIn: "Sign in to AstroCore",
    securityNote: "Secured by Supabase Auth · Data is encrypted",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
  },
  registerPage: {
    headline1: "Join the",
    headline2: "AI-First",
    headline3: "Workspace",
    subhead: "Create your AstroCore account and get instant access to a full AI agent workspace with multi-model support.",
    benefit1: "Unlimited AI agents",
    benefit2: "Persistent memory for agents",
    benefit3: "Sync across devices",
    benefit4: "Secure API key storage",
    benefit5: "Claude, GPT-4o, Gemini in one place",
    supportedProviders: "Supported Providers",
    memoryLayerActive: "Memory Layer Active",
    online: "Online",
    title: "Create account",
    subtitle: "New Operator Registration",
    nameLabel: "Name",
    namePlaceholder: "Your name or alias",
    emailLabel: "Email *",
    passwordLabel: "Password *",
    passwordPlaceholder: "At least 6 characters",
    fillFieldsError: "Fill in email and password",
    passwordTooShortError: "Password must be at least 6 characters",
    registering: "Registering...",
    join: "Join AstroCore",
    securityNote: "Secured by Supabase Auth · Data syncs across devices",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign in",
  },
  memory: {
    rename: "Rename",
    enterTitleError: "Enter a title",
    enterContentError: "Enter memory content",
    notAuthorizedError: "Not authorized",
    newEntryTitle: "New memory entry",
    layerLabel: "AI Memory Layer",
    nameField: "Title *",
    namePlaceholder: "Name of the context or knowledge...",
    contentField: "Content *",
    contentPlaceholder: "Context, information, instructions for the AI agent...",
    contentHint: "This content will be automatically injected into every agent request.",
    cancel: "Cancel",
    saving: "Saving...",
    saveToMemory: "Save to memory",
    saved: "Saved",
    collapse: "Collapse",
    expand: "Expand",
    activeContext: "Active Context",
    justNow: "just now",
    minAgo: "min ago",
    hourAgo: "h ago",
    yesterday: "yesterday",
    daysAgo: "d ago",
    emptyTitle: "Memory is empty",
    emptyDesc: "Add context, instructions, or knowledge. It will be automatically injected into every agent request.",
    persistentContext: "Persistent Context · Knowledge Engine",
    addMemory: "Add memory",
    contextActive: "Context active",
    memoryEmpty: "Memory is empty",
    entriesSuffix: "entries",
    title: "Memory",
    subtitle: "AI Memory Layer · Persistent Context · Knowledge Engine",
    injectedIntoAgents: "Injected into agents",
    newMemory: "New memory",
    statEntries: "Memory entries",
    statChars: "Context characters",
    statInjectedInto: "Injected into",
    statAllAgents: "all agents",
    howItWorksTitle: "How it works",
    howItWorksDesc: "All memory entries are automatically injected into every agent's system prompt. This lets agents know the context of your business, project, and behavior rules.",
    searchPlaceholder: "Search memory...",
    foundOfPrefix: "Found ",
    foundOfMid: " of ",
    foundOfSuffix: " entries",
    nothingFound: "Nothing found",
    deleteConfirmPrefix: 'Delete "',
    deleteConfirmSuffix: '"?',
  },
  providers: {
    openaiDesc: "GPT-4o, GPT-4 Turbo and other OpenAI models",
    anthropicDesc: "Claude Opus, Sonnet, and Haiku from Anthropic",
    googleDesc: "Gemini 2.0 Flash and Gemini Pro from Google",
    customDesc: "Your own AI provider or an OpenAI-compatible endpoint",
    enterApiKeyError: "Enter an API key",
    notAuthorizedError: "Not authorized",
    connectProviderTitle: "Connect a provider",
    apiControlLayer: "API Control Layer",
    providerField: "Provider",
    providerNamePlaceholder: "My AI provider...",
    providerNameField: "Provider name",
    modelField: "Model",
    apiKeyField: "API Key *",
    keysStoredNote: "Keys are stored in a secure Supabase database and tied to your account.",
    cancel: "Cancel",
    saving: "Saving...",
    connect: "Connect",
    active: "Active",
    disabled: "Disabled",
    apiKeyLabel: "API Key",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    deleteConfirmPrefix: 'Delete provider "',
    deleteConfirmSuffix: '"?',
    emptyTitle: "No providers connected",
    emptyDesc: "Connect OpenAI, Anthropic, Google Gemini, or your own AI provider so agents can respond.",
    modelGateway: "API Control Layer · Model Gateway",
    connectProvider: "Connect a provider",
    providerGatewayActive: "Provider Gateway Active",
    noActiveProviders: "No Active Providers",
    connectedSuffix: "connected",
    title: "Providers",
    subtitle: "API Control Layer · Model Gateway · connect AI models to your agents",
    activeSuffix: "active",
    connectBtn: "Connect",
    totalProviders: "Total providers",
    activeLabel: "Active",
    disabledLabel: "Disabled",
    securityNote: "API keys are stored in a secure Supabase database and tied to your account. Data syncs across devices.",
    connectAnother: "Connect another provider",
    webhookUrlField: "Endpoint URL",
    webhookUrlHint: "Your AI agent's base URL, OpenAI-API-compatible (e.g. https://your-agent.example.com/v1).",
    authHeaderField: "Authorization header (optional)",
    authHeaderHint: "If left blank, 'Bearer <API key>' is used by default.",
    customHeadersField: "Custom headers (JSON, optional)",
    customHeadersHint: "A string→string object, up to 20 fields. Example: { \"X-Org-Id\": \"12345\" }.",
    testConnectionBtn: "Test connection",
    testing: "Testing…",
    testSuccess: "Connection successful",
    testFailed: "Couldn't connect",
    testMissingFields: "Fill in the Endpoint URL, model, and API key before testing.",
    webhookRequiredError: "Enter an Endpoint URL for the Custom provider.",
    modelRequiredError: "Enter a model.",
    saveFailedError: "Couldn't save the provider.",
    statusConnected: "Connected",
    statusFailed: "Failed",
    statusUnverified: "Unverified",
  },
  vault: {
    enterTitleError: "Enter an entry title",
    enterContentError: "Enter entry content",
    notAuthorizedError: "Not authorized",
    newEntryTitle: "New entry",
    knowledgeVaultLabel: "AI Knowledge Vault",
    nameField: "Title *",
    namePlaceholder: "Name of the knowledge or topic...",
    contentField: "Content *",
    contentPlaceholder: "Text, note, AI reply, information...",
    tagsField: "Tags",
    tagsPlaceholder: "Add a tag and press Enter...",
    cancel: "Cancel",
    saving: "Saving...",
    saveEntry: "Save entry",
    copyContent: "Copy content",
    copyTitle: "Copy title",
    copied: "Copied",
    downloadMd: "Download .md",
    sendToObsidianTooltip: "Opens Obsidian via obsidian://new",
    openingEllipsis: "Opening…",
    sent: "Sent",
    failed: "Failed",
    sendToObsidian: "Send to Obsidian",
    close: "Close",
    deleteConfirmPrefix: 'Delete "',
    deleteConfirmSuffix: '"?',
    emptyTitle: "Vault is empty",
    emptyDesc: "Store knowledge, AI replies, notes, and any useful information.",
    addEntry: "Add entry",
    knowledgeBase: "AI Knowledge Vault · Knowledge Base",
    title: "Knowledge Vault",
    subtitle: "AI Knowledge Base · store and browse knowledge",
    newEntry: "New entry",
    entriesSuffix: "entries",
    statTotal: "Total entries",
    statUniqueTags: "Unique tags",
    statCharsSaved: "Characters saved",
    searchPlaceholder: "Search by title and content...",
    all: "All",
    foundOfPrefix: "Found ",
    foundOfMid: " of ",
    foundOfSuffix: " entries",
    clear: "Clear",
    nothingFound: "Nothing found",
    justNow: "just now",
    minAgo: "min ago",
    hourAgo: "h ago",
    yesterday: "yesterday",
    daysAgo: "d ago",
    obsidianVaultPrompt: "Enter your Obsidian vault name (as it appears in the vault list in Obsidian):",
  },
  forum: {
    title: "Forum",
    subtitle: "Community Layer · real-time AI discussions",
    categoriesTitle: "Categories",
    topicsCount: "topics",
    postsCount: "posts",
    newTopic: "New topic",
    newTopicTitle: "Create a topic",
    topicTitleField: "Title *",
    topicTitlePlaceholder: "What would you like to discuss?",
    topicContentField: "Message *",
    topicContentPlaceholder: "Describe it in more detail...",
    categoryField: "Category *",
    cancel: "Cancel",
    publish: "Publish",
    publishing: "Publishing...",
    titleRequiredError: "Enter a topic title",
    contentRequiredError: "Enter your message",
    categoryRequiredError: "Choose a category",
    loginToPost: "Sign in to post on the forum",
    loginBtn: "Sign in",
    backToForum: "Back to forum",
    backToCategory: "Back to category",
    noTopicsYet: "No topics yet",
    noTopicsHint: "Be the first to start a discussion in this category.",
    createFirstTopic: "Create the first topic",
    replyPlaceholder: "Write a reply...",
    sendReply: "Reply",
    sending: "Sending...",
    noRepliesYet: "No replies yet",
    noRepliesHint: "Be the first to reply.",
    repliesLabel: "replies",
    pinnedLabel: "Pinned",
    lockedLabel: "Locked",
    lockedNotice: "This topic is locked; new replies are disabled.",
    anonymousUser: "Member",
    liveIndicator: "Live",
    justNow: "just now",
    minAgo: "min ago",
    hourAgo: "h ago",
    yesterday: "yesterday",
    daysAgo: "d ago",
    loadError: "Couldn't load forum data.",
    postError: "Couldn't publish. Please try again.",
    deleteConfirm: "Delete this post?",
    delete: "Delete",
    topicsInCategory: "Topics",
    lastActivity: "Last activity",
    startedBy: "Started by",
  },
  gallery: {
    typeText: "Text",
    typeCode: "Code",
    typeImage: "Image",
    justNow: "just now",
    minAgo: "min",
    hourAgo: "h",
    yesterday: "yesterday",
    daysAgo: "d",
    saveOutputTitle: "Save output",
    layerLabel: "AI Output Gallery",
    typeOfOutput: "Output type",
    nameField: "Title *",
    namePlaceholder: "Output name...",
    contentField: "Content *",
    contentPlaceholderCode: "// Paste code...",
    contentPlaceholderImage: "Image URL or description...",
    contentPlaceholderText: "AI output text...",
    enterTitleError: "Enter a title",
    enterContentError: "Enter content",
    notAuthorizedError: "Not authorized",
    cancel: "Cancel",
    saving: "Saving...",
    save: "Save",
    deleteConfirmPrefix: 'Delete "',
    deleteConfirmSuffix: '"?',
    aiOutputLabel: "AI output",
    emptyTitle: "Gallery is empty",
    emptyDesc: "Store your best AI outputs — text, code, and images in one place.",
    addOutput: "Save output",
    savedGenerations: "AI Output Gallery · Saved Generations",
    title: "Gallery",
    subtitle: "AI Saved Generations · your best outputs in one place",
    outputsSuffix: "outputs",
    totalOutputs: "Total outputs",
    textsLabel: "Texts",
    codesLabel: "Code",
    imagesLabel: "Images",
    searchPlaceholder: "Search the gallery...",
    filterAll: "All",
    foundOfPrefix: "Found ",
    foundOfMid: " of ",
    clear: "Clear",
    nothingFound: "Nothing found",
  },
}

export const translations: Record<Language, typeof uk> = { uk, en }